import React, { useState } from 'react';
import { Download, X, Image as ImageIcon, Sparkles, Check, FileCode, Sliders } from 'lucide-react';

interface DiagramExportModalProps {
  isOpen: boolean;
  onClose: () => void;
  svgRef: React.RefObject<SVGSVGElement | null>;
  diagramTitle: string;
  defaultFilename?: string;
}

export type ExportFormat = 'png' | 'jpeg' | 'svg';
export type ExportResolution = '1x' | '2x' | '3x' | '4x';
export type ExportBackground = 'white' | 'dark' | 'transparent';

export const DiagramExportModal: React.FC<DiagramExportModalProps> = ({
  isOpen,
  onClose,
  svgRef,
  diagramTitle,
  defaultFilename = 'geochemical_diagram',
}) => {
  const [format, setFormat] = useState<ExportFormat>('png');
  const [resolution, setResolution] = useState<ExportResolution>('3x'); // Default to publication 300 DPI
  const [background, setBackground] = useState<ExportBackground>('white'); // Journal default
  const [includeHeader, setIncludeHeader] = useState<boolean>(true);
  const [customFilename, setCustomFilename] = useState<string>(defaultFilename);
  const [isExporting, setIsExporting] = useState<boolean>(false);
  const [exportSuccess, setExportSuccess] = useState<boolean>(false);

  if (!isOpen) return null;

  const resolutionScaleMap: Record<ExportResolution, { scale: number; label: string; dpi: string }> = {
    '1x': { scale: 1, label: 'Standard Web (1x)', dpi: '72 DPI (~800×700 px)' },
    '2x': { scale: 2, label: 'High Resolution (2x)', dpi: '150 DPI (~1600×1400 px)' },
    '3x': { scale: 3, label: 'Publication Quality (3x)', dpi: '300 DPI (~2400×2100 px - Recommended for Papers)' },
    '4x': { scale: 4, label: 'Archival Ultra-HD (4x)', dpi: '600 DPI (~3200×2800 px)' },
  };

  const handleExport = async () => {
    if (!svgRef.current) return;
    setIsExporting(true);

    try {
      const svg = svgRef.current;
      const bbox = svg.getBoundingClientRect();
      const baseWidth = bbox.width || 800;
      const baseHeight = bbox.height || 700;
      const scale = resolutionScaleMap[resolution].scale;

      // Clean clone of the SVG
      const clonedSvg = svg.cloneNode(true) as SVGSVGElement;
      clonedSvg.setAttribute('width', `${baseWidth}`);
      clonedSvg.setAttribute('height', `${baseHeight}`);

      // If background is white and in dark mode, adjust text styling if needed
      const bgColor =
        background === 'white'
          ? '#ffffff'
          : background === 'dark'
          ? '#0c0a09'
          : 'transparent';

      if (format === 'svg') {
        // Direct SVG Vector Export
        const svgHeader = '<?xml version="1.0" encoding="utf-8"?>\n';
        const svgData = new XMLSerializer().serializeToString(clonedSvg);
        const blob = new Blob([svgHeader + svgData], { type: 'image/svg+xml;charset=utf-8' });
        const url = URL.createObjectURL(blob);
        const link = document.createElement('a');
        link.href = url;
        link.download = `${customFilename || 'diagram'}.svg`;
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
        URL.revokeObjectURL(url);
      } else {
        // Raster Export (PNG or JPEG) via Canvas
        const headerHeight = includeHeader ? 50 * scale : 0;
        const canvas = document.createElement('canvas');
        canvas.width = baseWidth * scale;
        canvas.height = baseHeight * scale + headerHeight;
        const ctx = canvas.getContext('2d');

        if (!ctx) throw new Error('Could not initialize canvas context');

        // Draw background
        if (bgColor !== 'transparent') {
          ctx.fillStyle = bgColor;
          ctx.fillRect(0, 0, canvas.width, canvas.height);
        }

        // Draw publication header if enabled
        if (includeHeader) {
          ctx.fillStyle = background === 'white' ? '#1c1917' : '#f5f5f4';
          ctx.font = `bold ${14 * scale}px "Plus Jakarta Sans", sans-serif`;
          ctx.fillText(diagramTitle, 24 * scale, 30 * scale);

          ctx.fillStyle = background === 'white' ? '#78716c' : '#a8a29e';
          ctx.font = `${10 * scale}px "Plus Jakarta Sans", sans-serif`;
          const subtext = `Generated by PetroGeochem Studio • ${new Date().toLocaleDateString(undefined, { year: 'numeric', month: 'short', day: 'numeric' })}`;
          ctx.fillText(subtext, 24 * scale, 45 * scale);

          // Subtle divider line
          ctx.strokeStyle = background === 'white' ? '#e7e5e4' : '#292524';
          ctx.lineWidth = 1 * scale;
          ctx.beginPath();
          ctx.moveTo(16 * scale, 48 * scale);
          ctx.lineTo(canvas.width - 16 * scale, 48 * scale);
          ctx.stroke();
        }

        // Convert SVG to Image and draw to canvas
        const svgData = new XMLSerializer().serializeToString(clonedSvg);
        const svgBlob = new Blob([svgData], { type: 'image/svg+xml;charset=utf-8' });
        const blobUrl = URL.createObjectURL(svgBlob);

        const img = new Image();
        img.onload = () => {
          ctx.drawImage(img, 0, headerHeight, baseWidth * scale, baseHeight * scale);
          URL.revokeObjectURL(blobUrl);

          const mimeType = format === 'jpeg' ? 'image/jpeg' : 'image/png';
          canvas.toBlob(
            (blob) => {
              if (blob) {
                const url = URL.createObjectURL(blob);
                const link = document.createElement('a');
                link.href = url;
                link.download = `${customFilename || 'diagram'}.${format}`;
                document.body.appendChild(link);
                link.click();
                document.body.removeChild(link);
                URL.revokeObjectURL(url);
              }
              setIsExporting(false);
              setExportSuccess(true);
              setTimeout(() => setExportSuccess(false), 2500);
            },
            mimeType,
            format === 'jpeg' ? 0.95 : undefined
          );
        };
        img.onerror = () => {
          URL.revokeObjectURL(blobUrl);
          setIsExporting(false);
          alert('Failed to render diagram image. Please try SVG format.');
        };
        img.src = blobUrl;
        return;
      }

      setIsExporting(false);
      setExportSuccess(true);
      setTimeout(() => setExportSuccess(false), 2500);
    } catch (err) {
      console.error('Export error:', err);
      setIsExporting(false);
      alert('An error occurred during figure export.');
    }
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/80 backdrop-blur-sm animate-in fade-in duration-150">
      <div className="bg-stone-900 border border-stone-800 rounded-2xl max-w-lg w-full p-6 shadow-2xl space-y-6">
        {/* Modal Header */}
        <div className="flex items-center justify-between pb-4 border-b border-stone-800">
          <div className="flex items-center gap-2.5">
            <div className="w-9 h-9 rounded-xl bg-amber-500/10 border border-amber-500/20 flex items-center justify-center text-amber-400">
              <Download className="w-5 h-5" />
            </div>
            <div>
              <h3 className="text-sm font-bold text-stone-100">Export High-Resolution Figure</h3>
              <p className="text-xs text-stone-400">Custom DPI and vector publication export</p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="p-1.5 text-stone-400 hover:text-white rounded-lg hover:bg-stone-800 transition-colors"
          >
            <X className="w-4 h-4" />
          </button>
        </div>

        {/* Configuration Options */}
        <div className="space-y-4 text-xs">
          {/* Output Format */}
          <div>
            <label className="block font-semibold text-stone-300 mb-2">Export Format</label>
            <div className="grid grid-cols-3 gap-2">
              <button
                type="button"
                onClick={() => setFormat('png')}
                className={`py-2 px-3 rounded-lg border text-center font-medium transition-all ${
                  format === 'png'
                    ? 'bg-amber-600 text-white border-amber-500 shadow'
                    : 'bg-stone-800 text-stone-300 border-stone-700 hover:bg-stone-750'
                }`}
              >
                <div className="font-bold">PNG</div>
                <div className="text-[10px] opacity-80">Lossless Raster</div>
              </button>
              <button
                type="button"
                onClick={() => {
                  setFormat('jpeg');
                  if (background === 'transparent') setBackground('white');
                }}
                className={`py-2 px-3 rounded-lg border text-center font-medium transition-all ${
                  format === 'jpeg'
                    ? 'bg-amber-600 text-white border-amber-500 shadow'
                    : 'bg-stone-800 text-stone-300 border-stone-700 hover:bg-stone-750'
                }`}
              >
                <div className="font-bold">JPEG</div>
                <div className="text-[10px] opacity-80">High Contrast</div>
              </button>
              <button
                type="button"
                onClick={() => setFormat('svg')}
                className={`py-2 px-3 rounded-lg border text-center font-medium transition-all ${
                  format === 'svg'
                    ? 'bg-amber-600 text-white border-amber-500 shadow'
                    : 'bg-stone-800 text-stone-300 border-stone-700 hover:bg-stone-750'
                }`}
              >
                <div className="font-bold">SVG</div>
                <div className="text-[10px] opacity-80">Vector Scalable</div>
              </button>
            </div>
          </div>

          {/* Resolution / DPI (for raster) */}
          {format !== 'svg' && (
            <div>
              <label className="block font-semibold text-stone-300 mb-2 flex items-center justify-between">
                <span>Output Resolution &amp; DPI</span>
                <span className="text-[11px] text-amber-400 font-normal">
                  {resolutionScaleMap[resolution].dpi}
                </span>
              </label>
              <div className="grid grid-cols-2 sm:grid-cols-4 gap-2">
                {(['1x', '2x', '3x', '4x'] as ExportResolution[]).map((res) => (
                  <button
                    key={res}
                    type="button"
                    onClick={() => setResolution(res)}
                    className={`py-2 px-2.5 rounded-lg border text-center font-medium transition-all ${
                      resolution === res
                        ? 'bg-amber-600 text-white border-amber-500 shadow'
                        : 'bg-stone-800 text-stone-300 border-stone-700 hover:bg-stone-750'
                    }`}
                  >
                    <div className="font-bold">{res}</div>
                    <div className="text-[9px] opacity-80">{res === '3x' ? 'Publication' : res === '4x' ? 'Archival' : res === '2x' ? 'High-DPI' : 'Standard'}</div>
                  </button>
                ))}
              </div>
            </div>
          )}

          {/* Canvas Background */}
          <div>
            <label className="block font-semibold text-stone-300 mb-2">Canvas Background Theme</label>
            <div className="grid grid-cols-3 gap-2">
              <button
                type="button"
                onClick={() => setBackground('white')}
                className={`py-2 px-3 rounded-lg border text-center font-medium transition-all ${
                  background === 'white'
                    ? 'bg-amber-600 text-white border-amber-500 shadow'
                    : 'bg-stone-800 text-stone-300 border-stone-700 hover:bg-stone-750'
                }`}
              >
                <div className="font-bold">White Paper</div>
                <div className="text-[10px] opacity-80">Journal Standard</div>
              </button>
              <button
                type="button"
                onClick={() => setBackground('dark')}
                className={`py-2 px-3 rounded-lg border text-center font-medium transition-all ${
                  background === 'dark'
                    ? 'bg-amber-600 text-white border-amber-500 shadow'
                    : 'bg-stone-800 text-stone-300 border-stone-700 hover:bg-stone-750'
                }`}
              >
                <div className="font-bold">Dark Canvas</div>
                <div className="text-[10px] opacity-80">Slide Presentation</div>
              </button>
              <button
                type="button"
                disabled={format === 'jpeg'}
                onClick={() => setBackground('transparent')}
                className={`py-2 px-3 rounded-lg border text-center font-medium transition-all ${
                  format === 'jpeg'
                    ? 'opacity-40 cursor-not-allowed bg-stone-900 border-stone-800 text-stone-600'
                    : background === 'transparent'
                    ? 'bg-amber-600 text-white border-amber-500 shadow'
                    : 'bg-stone-800 text-stone-300 border-stone-700 hover:bg-stone-750'
                }`}
              >
                <div className="font-bold">Transparent</div>
                <div className="text-[10px] opacity-80">PNG Only</div>
              </button>
            </div>
          </div>

          {/* Include Metadata Header Toggle */}
          {format !== 'svg' && (
            <div className="pt-2 border-t border-stone-800 flex items-center justify-between">
              <div>
                <span className="font-semibold text-stone-200 block">Include Figure Header Banner</span>
                <span className="text-[11px] text-stone-400">Embeds diagram title, author citation, and timestamp</span>
              </div>
              <input
                type="checkbox"
                checked={includeHeader}
                onChange={(e) => setIncludeHeader(e.target.checked)}
                className="w-4 h-4 rounded text-amber-500 bg-stone-950 border-stone-700 focus:ring-amber-500"
              />
            </div>
          )}

          {/* File Name */}
          <div>
            <label className="block font-semibold text-stone-300 mb-1">File Name</label>
            <div className="flex items-center bg-stone-950 border border-stone-800 rounded-lg px-3 py-1.5 focus-within:border-amber-500">
              <input
                type="text"
                value={customFilename}
                onChange={(e) => setCustomFilename(e.target.value)}
                className="bg-transparent text-stone-200 text-xs w-full focus:outline-none"
                placeholder="filename"
              />
              <span className="text-stone-500 text-xs font-mono ml-2">.{format}</span>
            </div>
          </div>
        </div>

        {/* Actions */}
        <div className="flex items-center justify-end gap-3 pt-4 border-t border-stone-800">
          <button
            type="button"
            onClick={onClose}
            className="px-4 py-2 text-xs font-medium text-stone-400 hover:text-white rounded-lg hover:bg-stone-800 transition-colors"
          >
            Cancel
          </button>
          <button
            type="button"
            disabled={isExporting}
            onClick={handleExport}
            className="px-4 py-2 text-xs font-semibold bg-amber-600 hover:bg-amber-500 text-white rounded-lg shadow-sm transition-all flex items-center gap-1.5 disabled:opacity-50"
          >
            {exportSuccess ? (
              <>
                <Check className="w-3.5 h-3.5 text-emerald-300" />
                <span>Downloaded!</span>
              </>
            ) : isExporting ? (
              <span>Generating...</span>
            ) : (
              <>
                <Download className="w-3.5 h-3.5" />
                <span>Download Figure</span>
              </>
            )}
          </button>
        </div>
      </div>
    </div>
  );
};
