import { MineralReference, RockReference } from '../types/geochem';
import { getDatabaseRefs } from './externalDatabases';

export interface VisualSpecimenData {
  formula: string;
  typicalOccurrence: string;
  imageUrl: string;
  imageCaption: string;
  geologicalFacts: string[];
  fieldPhotoUrl?: string;
  thinSectionUrl?: string;
}

/**
 * Curated Visual Database for Minerals and Rocks
 * High-resolution imagery from Wikimedia Commons and geological archives,
 * complete chemical formulas, tectonic/occurrence context, and peer-reviewed geological facts.
 */
export const VISUAL_DATA_MAP: Record<string, VisualSpecimenData> = {
  // ==========================================
  // --- VOLCANIC ROCKS ---
  // ==========================================
  'rock-n-morb': {
    formula: 'Plag (An₅₀₋₇₀) + Cpx (Augite) ± Ol (Fo₈₀) ± Ti-Mt',
    typicalOccurrence: 'Mid-Ocean Ridge spreading centers (East Pacific Rise, Mid-Atlantic Ridge); comprises oceanic crust Layer 2A/2B at 2,000–4,000 m water depth.',
    imageUrl: 'https://images.unsplash.com/photo-1533038590840-1cde6e668a91?auto=format&fit=crop&w=900&q=80',
    imageCaption: 'Aphanitic basaltic oceanic crust hand specimen with fine plagioclase micro-laths and glassy margin.',
    geologicalFacts: [
      'Normal Mid-Ocean Ridge Basalt (N-MORB) is the most volumetrically abundant volcanic rock on Earth, covering more than 60% of the planetary crust.',
      'Circulation of seawater through fractured hot MORB lavas fuels deep-sea hydrothermal "black smoker" vents at ~350°C, hosting chemosynthetic life.',
      'Geochemically depleted in light rare earth elements (LREE) and potassium because its mantle source underwent prior melting episodes during Earth history.',
    ],
  },
  'rock-e-morb': {
    formula: 'Plagioclase (An₆₅) + Titanaugite + Olivine + Ilmenite',
    typicalOccurrence: 'Ridge-hotspot interaction zones (e.g. Galápagos Spreading Center, Reykjanes Ridge south of Iceland) where a mantle plume impinges on a divergent ridge.',
    imageUrl: 'https://images.unsplash.com/photo-1525857597365-5f6dbff2e36e?auto=format&fit=crop&w=900&q=80',
    imageCaption: 'Dark vesicular basalt with visible pyroxene and plagioclase microphenocrysts.',
    geologicalFacts: [
      'Unlike N-MORB, E-MORB is "enriched" in incompatible elements (K, Ti, P, LREE) due to contribution from deeper, undepleted mantle plume material.',
      'Provides a direct geochemical tracer allowing geochemists to map mantle plume dispersion along mid-ocean ridge axes for thousands of kilometers.',
      'Crystallizes titanaugite clinopyroxene with distinctive violet-brown pleochroism under cross-polarized petrographic microscopy.',
    ],
  },
  'rock-oib-tholeiite': {
    formula: 'Olivine (Fo₈₂₋₈₈) + Augite + Labradorite + Ilmenite',
    typicalOccurrence: 'Subaerial and submarine shield-building volcanic stages over intraplate mantle hotspots (e.g., Kilauea and Mauna Loa, Hawaii).',
    imageUrl: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=900&q=80',
    imageCaption: 'Vesicular tholeiitic basalt with golden-green olivine phenocrysts from Hawaiian lava flow.',
    geologicalFacts: [
      'Mauna Loa is the largest active volcano on Earth, constructed almost entirely from stacked flows of Hawaiian tholeiitic shield basalt reaching 9 km from ocean floor to summit.',
      'Erupts at temperatures between 1,150°C and 1,200°C with extremely low viscosity, forming both fluid "Pāhoehoe" ropey lava and rubbly "ʻAʻā" flows.',
      'High FeOT and TiO2 signatures distinguish ocean island basalts from ridge basalts, reflecting a deeper, less degassed mantle source.',
    ],
  },
  'rock-oib-alkali-basalt': {
    formula: 'Titanaugite + Olivine + Labradorite + Nepheline (normative) + Apatite',
    typicalOccurrence: 'Post-shield capping and rejuvenated volcanic stages of oceanic hotspots (e.g., Tahiti, Canary Islands, Azores, Oahu).',
    imageUrl: 'https://images.unsplash.com/photo-1590412200988-a436970781fa?auto=format&fit=crop&w=900&q=80',
    imageCaption: 'Dense alkali basalt specimen containing dark titaniferous augite and mantle xenolith fragments.',
    geologicalFacts: [
      'Generated by smaller degrees of partial melting (<5-10%) at greater mantle depths (>60-80 km), concentrating alkalis (Na₂O + K₂O > 4 wt%).',
      'Frequently carries dense green mantle peridotite (lherzolite/dunite) xenoliths brought to the surface in hours from depths exceeding 50 km.',
      'Contains normative nepheline due to silica undersaturation, preventing the crystallization of free quartz.',
    ],
  },
  'rock-cfb-continental-flood': {
    formula: 'Plagioclase (Andesine-Labradorite) + Augite + Pigeonite + Titanomagnetite + Qtz',
    typicalOccurrence: 'Continental Large Igneous Provinces (LIPs) formed during supercontinent breakup (Columbia River Basalts, Deccan Traps, Siberian Traps, Karoo).',
    imageUrl: 'https://images.unsplash.com/photo-1525857597365-5f6dbff2e36e?auto=format&fit=crop&w=900&q=80',
    imageCaption: 'Columnar jointed continental flood basalt basaltic hand specimen with microcrystalline groundmass.',
    geologicalFacts: [
      'The Siberian Traps (~252 Ma) erupted over 3 million cubic kilometers of basalt, triggering the Permian-Triassic extinction ("The Great Dying") that wiped out 95% of marine life.',
      'The Deccan Traps in India erupted right around the Cretaceous-Paleogene boundary (~66 Ma), coincident with the asteroid impact that ended the age of dinosaurs.',
      'Shows diagnostic enrichment in crustal elements (elevated SiO2, K2O, and 87Sr/86Sr) due to assimilation of continental crust as magma ascended through cratonic roots.',
    ],
  },
  'rock-picrite': {
    formula: 'Olivine (Fo₈₈₋₉₁ > 30 vol%) + Chromite + Clinopyroxene + Plagioclase',
    typicalOccurrence: 'High-temperature volcanic suites, deep ocean island conduits, and proto-rift stages (Réunion Island, Karoo, Iceland, Hawaii).',
    imageUrl: 'https://images.unsplash.com/photo-1533038590840-1cde6e668a91?auto=format&fit=crop&w=900&q=80',
    imageCaption: 'Olivine-rich oceanite picrite displaying abundant emerald-green olivine crystals embedded in dark basaltic matrix.',
    geologicalFacts: [
      'Picrite is a high-magnesium basalt containing over 18 wt% MgO, representing either very high-temperature primitive melts or olivine-accumulative magmas.',
      'Liquid eruption temperatures for picritic melts exceed 1,350°C to 1,450°C, significantly hotter than regular basalts.',
      'The iconic oceanite variety found on Réunion Island contains over 50% cumulate olivine phenocrysts.',
    ],
  },
  'rock-komatiite': {
    formula: 'Skeletal Olivine (Fo₉₀₋₉₄) + Skeletal Pyroxene + Chromite (MgO > 24 wt%)',
    typicalOccurrence: 'Archean greenstone belts (>2.5 billion years old) in South Africa (Barberton), Canada (Abitibi), and Australia (Yilgarn Craton).',
    imageUrl: 'https://images.unsplash.com/photo-1525857597365-5f6dbff2e36e?auto=format&fit=crop&w=900&q=80',
    imageCaption: 'Polished cut section of Archean komatiite showing macroscopic spinifex texture with radiating blades of olivine.',
    geologicalFacts: [
      'Erupted at staggering temperatures between 1,550°C and 1,650°C during the Archean Eon, when Earth\'s mantle was 200–300°C hotter than today.',
      'Named after the Komati River in South Africa where it was first identified by Morris and Richard Viljoen in 1969.',
      'Displays the famous "spinifex texture"—radiating crystalline needles of olivine that quenched instantly upon contact with cold Archean seawater.',
    ],
  },
  'rock-basaltic-andesite': {
    formula: 'Labradorite-Andesine + Augite + Hypersthene + Magnetite',
    typicalOccurrence: 'Subduction zone volcanic arcs (Cascades, Aleutians, Central America, Kamchatka); transitional intermediate volcanism.',
    imageUrl: 'https://images.unsplash.com/photo-1567095761054-7a02e69e5c43?auto=format&fit=crop&w=900&q=80',
    imageCaption: 'Medium-dark grey porphyritic basaltic andesite with visible zoned plagioclase phenocrysts.',
    geologicalFacts: [
      'Forms when mantle-derived basaltic melts differentiate and assimilate continental or island-arc crust, raising SiO₂ to 52–57 wt%.',
      'Commonly carries both clinopyroxene (augite) and orthopyroxene (hypersthene), reflecting subalkaline calc-alkaline crystallization.',
      'Forms the lower flanks of explosive stratovolcanoes like Mount St. Helens and Mount Rainier in the Pacific Northwest.',
    ],
  },
  'rock-calc-alk-andesite': {
    formula: 'Andesine Plagioclase (An₄₀) + Hornblende + Augite/Opx + Magnetite',
    typicalOccurrence: 'Continental volcanic arcs and convergent margins (Andes Mountain Range, Japan Arc, Cascade Range).',
    imageUrl: 'https://images.unsplash.com/photo-1588345921523-c2dcdb7f1dcd?auto=format&fit=crop&w=900&q=80',
    imageCaption: 'Classic porphyritic andesite featuring prominent white andesine phenocrysts and black hornblende needles in grey groundmass.',
    geologicalFacts: [
      'Named after South America\'s Andes Mountains, which represent the premier modern active continental subduction volcanic arc.',
      'Hydrous minerals like hornblende and biotite reflect the critical role of subducted slab-derived water in depressing mantle wedge melting points.',
      'Andesitic eruptions are notorious for explosive Plinian columns, glowing pyroclastic density currents, and block-and-ash flows.',
    ],
  },
  'rock-dacite': {
    formula: 'Oligoclase-Andesine + Quartz (groundmass) + Hornblende + Biotite ± Cpx',
    typicalOccurrence: 'Viscous volcanic dome complexes, explosive caldera eruptions (Mount St. Helens 1980 dome, Mount Pinatubo, Santorini).',
    imageUrl: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=900&q=80',
    imageCaption: 'Light grey porphyritic dacite dome rock with glassy microcrystalline matrix and hornblende phenocrysts.',
    geologicalFacts: [
      'The catastrophic May 18, 1980 lateral blast of Mount St. Helens was driven by the collapse of a cryptodome of high-silica dacite magma.',
      'Because of high silica (63–69 wt%) and lower temperatures (~800–900°C), dacitic magma has immense viscosity and typically piles up as steep volcanic domes.',
      'Contains quartz phenocrysts that often exhibit resorption rims and embayments due to magma mixing prior to eruption.',
    ],
  },
  'rock-rhyolite-high-silica': {
    formula: 'Quartz + Sanidine/Anorthoclase + Albite + Biotite (SiO₂ > 75 wt%)',
    typicalOccurrence: 'Supervolcano calderas and continental intraplate hot spots (Yellowstone Caldera, Taupo New Zealand, Valles Caldera, Bishop Tuff).',
    imageUrl: 'https://images.unsplash.com/photo-1533038590840-1cde6e668a91?auto=format&fit=crop&w=900&q=80',
    imageCaption: 'Pinkish-buff high-silica rhyolite with flow banding and quartz-sanidine phenocrysts.',
    geologicalFacts: [
      'Yellowstone Caldera\'s colossal Lava Creek Tuff eruption (~631,000 years ago) ejected over 1,000 cubic kilometers of high-silica rhyolite pumice and ash.',
      'Rhyolitic melt is the volcanic extrusive equivalent of granite, possessing the highest viscosity of all common lavas (100 million times more viscous than basalt).',
      'Rapid cooling of dry rhyolite produces black natural volcanic glass known as obsidian, prized by ancient civilizations for surgical-sharp tools.',
    ],
  },
  'rock-peralkaline-pantellerite': {
    formula: 'Anorthoclase + Aegirine + Cossyrite (Aenigmatite) + Quartz',
    typicalOccurrence: 'Continental rift valleys and oceanic hotspot islands (Pantelleria Island in Mediterranean, Ethiopian Rift Valley, Kenya Rift).',
    imageUrl: 'https://images.unsplash.com/photo-1525857597365-5f6dbff2e36e?auto=format&fit=crop&w=900&q=80',
    imageCaption: 'Dark green-grey peralkaline pantellerite showing aegirine-augite needles and glassy sanidine phenocrysts.',
    geologicalFacts: [
      'Pantellerite is peralkaline, meaning the molar ratio (Na+K)/Al > 1; the excess alkalis force the crystallization of exotic minerals like aegirine and cossyrite.',
      'Despite having >68 wt% SiO₂, the high dissolved alkali and halogen (F, Cl) content depresses melt viscosity, allowing it to form thin, extensive lava flows.',
      'Named after Pantelleria, an Italian volcanic island southwest of Sicily.',
    ],
  },
  'rock-trachyte': {
    formula: 'Sanidine / Anorthoclase (>60%) + Plagioclase + Biotite ± Augite',
    typicalOccurrence: 'Alkaline volcanic provinces, intraplate continental rifts, and oceanic islands (Phlegraean Fields Italy, Mount Kenya, Ascension Island).',
    imageUrl: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=900&q=80',
    imageCaption: 'Light grey trachyte hand sample exhibiting characteristic rough fracture and aligned feldspar laths (trachytic texture).',
    geologicalFacts: [
      'Its name derives from the Greek "trachys" (τραγύς), meaning "rough", describing the distinctive sandpaper-like rough feel of its fracture surfaces.',
      'Displays a characteristic microscopic "trachytic texture" where tiny subparallel sanidine feldspar laths flow around phenocrysts.',
      'The Campi Flegrei supervolcano near Naples, Italy produced colossal trachytic ignimbrite sheets (Campanian Ignimbrite, ~39 ka).',
    ],
  },
  'rock-phonolite': {
    formula: 'Sanidine + Nepheline + Aegirine-Augite ± Nosean ± Sodalite',
    typicalOccurrence: 'Strongly alkaline volcanic fields, intraplate diatremes, and rift systems (Devils Tower Wyoming, Mount Erebus Antarctica, Kenya Rift).',
    imageUrl: 'https://images.unsplash.com/photo-1567095761054-7a02e69e5c43?auto=format&fit=crop&w=900&q=80',
    imageCaption: 'Greenish-grey phonolite specimen from Devils Tower featuring nepheline and sanidine crystals.',
    geologicalFacts: [
      'Devils Tower in Wyoming, USA—the first designated US National Monument—is a world-famous 386-meter phonolite porphyry columnar laccolith/volcanic conduit.',
      'Named "phonolite" (meaning "ringing stone" in Greek) because thin slabs of this fine, dense rock ring musically like a metal bell when struck with a rock hammer.',
      'Mount Erebus in Antarctica is home to a permanent phonolite lava lake, one of the only active phonolite magma lakes on Earth.',
    ],
  },
  'rock-tephrite-basanite': {
    formula: 'Titanaugite + Olivine (Fo₇₅₋₈₅) + Plagioclase + Nepheline / Leucite + Titanomagnetite',
    typicalOccurrence: 'Intracontinental rifting, alkaline diatremes, and ocean island hotspot margins (Eifel volcanic field Germany, Massif Central France).',
    imageUrl: 'https://images.unsplash.com/photo-1590412200988-a436970781fa?auto=format&fit=crop&w=900&q=80',
    imageCaption: 'Dark melanocratic basanite with abundant olivine nodules and black titanaugite phenocrysts.',
    geologicalFacts: [
      'Basanite is a silica-undersaturated mafic rock containing both olivine (>10% modal or normative) and feldspathoids (nepheline or leucite).',
      'Generated by low-degree partial melting of carbonated or hydrous mantle peridotite at depths between 70 and 100 km.',
      'Frequently serves as the carrier magma for peridotite mantle xenoliths and deep-seated megacrysts.',
    ],
  },
  'rock-foidite-nephelinite': {
    formula: 'Nepheline + Clinopyroxene (Titanaugite) + Melilite ± Perovskite ± Apatite',
    typicalOccurrence: 'Ultra-alkaline volcanic centers and continental rift diatremes (East African Rift, Nyiragongo DRC, Mount Vesuvius).',
    imageUrl: 'https://images.unsplash.com/photo-1525857597365-5f6dbff2e36e?auto=format&fit=crop&w=900&q=80',
    imageCaption: 'Extremely silica-poor nephelinite specimen with interlocking nepheline and dark titanaugite.',
    geologicalFacts: [
      'Foidites have total feldspathoids exceeding feldspar in the QAPF classification, representing some of the most silica-undersaturated silicate rocks on Earth.',
      'Mount Nyiragongo in the Democratic Republic of Congo erupts melilite-nephelinite lavas that flow at speeds exceeding 60 km/h due to exceptionally low viscosity.',
      'Rich in rare earth elements, niobium, and titanium, often associated with carbonatite complexes.',
    ],
  },
  'rock-boninite': {
    formula: 'Protoenstatite / Clinoenstatite + Bronzite + Olivine + High-Si Glass',
    typicalOccurrence: 'Subduction initiation fore-arc environments (Izu-Bonin-Mariana Arc, Bonin Islands Japan, Troodos ophiolite Cyprus).',
    imageUrl: 'https://images.unsplash.com/photo-1533038590840-1cde6e668a91?auto=format&fit=crop&w=900&q=80',
    imageCaption: 'Fore-arc boninite specimen displaying bronzite phenocrysts in dark glassy groundmass.',
    geologicalFacts: [
      'Named after the Bonin Islands (Ogasawara) south of Japan, where it was first discovered.',
      'Possesses a unique, paradoxical geochemical signature: high MgO (>8 wt%) together with high SiO₂ (>52 wt%) and ultra-low TiO₂ (<0.5 wt%).',
      'Marks the spontaneous initiation of oceanic subduction, generated by shallow re-melting of refractory depleted mantle fluxed by water from the sinking slab.',
    ],
  },
  'rock-carbonatite-natro': {
    formula: 'Calcite / Dolomite / Nyerereite + Gregoryite (CO₂ > 35 wt%, SiO₂ < 10 wt%)',
    typicalOccurrence: 'Continental rift systems and alkaline igneous complexes (Ol Doinyo Lengai Tanzania, Fen Norway, Mountain Pass California).',
    imageUrl: 'https://images.unsplash.com/photo-1588345921523-c2dcdb7f1dcd?auto=format&fit=crop&w=900&q=80',
    imageCaption: 'Rare volcanic carbonatite lava showing dark sodium-carbonate crust that turns white upon exposure to atmospheric moisture.',
    geologicalFacts: [
      'Ol Doinyo Lengai ("Mountain of God" in Maasai) in Tanzania is the only active carbonatite volcano on Earth, erupting black sodium-rich carbonate lavas at just 510°C.',
      'At night, the lavas glow with a dull orange-red luminescence; upon contact with rainwater, the black natrocarbonatite turns chalky white in hours.',
      'Carbonatite intrusions are the world\'s primary source of critical rare earth elements (REE), niobium, and tantalum (e.g., Mountain Pass, CA).',
    ],
  },

  // ==========================================
  // --- PLUTONIC ROCKS ---
  // ==========================================
  'rock-granite-i-type': {
    formula: 'Quartz (25-35%) + K-Feldspar (Orthoclase/Microcline) + Plagioclase (Oligoclase) + Hornblende + Biotite',
    typicalOccurrence: 'Continental margin magmatic arcs and batholiths (Sierra Nevada Batholith, Coastal Batholith of Peru, Idaho Batholith).',
    imageUrl: 'https://images.unsplash.com/photo-1567095761054-7a02e69e5c43?auto=format&fit=crop&w=900&q=80',
    imageCaption: 'Coarse phaneritic Sierra Nevada granite exhibiting interlocking quartz, white plagioclase, pink K-feldspar, and black hornblende.',
    geologicalFacts: [
      '"I-Type" signifies igneous protolith: derived from the melting of deep, previously unweathered igneous rocks in subduction arcs.',
      'Characterized by hornblende, magnetite (making it magnetic), and molar A/CNK < 1.1 (metaluminous to mildly peraluminous).',
      'Forms iconic monolithic geomorphic features such as El Capitan and Half Dome in Yosemite National Park.',
    ],
  },
  'rock-granite-s-type': {
    formula: 'Quartz + K-Feldspar + Plagioclase + Biotite + Muscovite ± Garnet ± Cordierite',
    typicalOccurrence: 'Continental collision zones and crustal suture belts (Himalayan leucogranites, Lachlan Fold Belt Australia, European Variscan Belt).',
    imageUrl: 'https://images.unsplash.com/photo-1533038590840-1cde6e668a91?auto=format&fit=crop&w=900&q=80',
    imageCaption: 'Peraluminous S-type granite containing visible silvery muscovite books and tiny red almandine garnets.',
    geologicalFacts: [
      '"S-Type" stands for sedimentary protolith: formed by the crustal anatexis (melting) of clay-rich pelitic sedimentary rocks during continental collision.',
      'Peraluminous geochemistry (molar Al₂O₃ > CaO + Na₂O + K₂O) forces the crystallization of aluminium-rich minerals like muscovite, garnet, and cordierite.',
      'Lacks hornblende and has low magnetite, instead containing ilmenite, giving it a very low magnetic susceptibility.',
    ],
  },
  'rock-granodiorite': {
    formula: 'Plagioclase (Andesine/Oligoclase 40-50%) + Quartz (20-30%) + K-Feldspar (10-15%) + Biotite + Hornblende',
    typicalOccurrence: 'Continental arc batholiths; the most voluminous plutonic component of the upper continental crust (Sierra Nevada, Peninsular Ranges).',
    imageUrl: 'https://images.unsplash.com/photo-1525857597365-5f6dbff2e36e?auto=format&fit=crop&w=900&q=80',
    imageCaption: 'Granodiorite hand sample showing intermediate salt-and-pepper texture with more plagioclase than K-feldspar.',
    geologicalFacts: [
      'Granodiorite is the plutonic intrusive equivalent of dacite and is significantly more abundant in continental batholiths than true granite.',
      'The famous Rosetta Stone, which unlocked the translation of Egyptian hieroglyphics, was carved from a slab of granodiorite.',
      'Mount Rushmore National Memorial in South Dakota is carved directly into Proterozoic Harney Peak granodiorite.',
    ],
  },
  'rock-tonalite': {
    formula: 'Plagioclase (Oligoclase/Andesine > 50%) + Quartz (>20%) + Hornblende + Biotite (K-feldspar < 10%)',
    typicalOccurrence: 'Archean cratonic shields (TTG - Tonalite-Trondhjemite-Granodiorite suites) and subduction arc roots (Adamello Massif Alps).',
    imageUrl: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=900&q=80',
    imageCaption: 'Coarse phaneritic tonalite hand sample from deep continental arc crust showing dominant white plagioclase and quartz.',
    geologicalFacts: [
      'TTG (Tonalite-Trondhjemite-Granodiorite) suites comprise over 70% of Archean continental crust, recording the birth of Earth\'s first stable continents.',
      'Formed by high-pressure partial melting of hydrous basalt (amphibolite/eclogite) where garnet remained in the residue, leaving high Na and low Y/Yb.',
      'Named after the Tonale Pass in the Italian Alps.',
    ],
  },
  'rock-gabbro': {
    formula: 'Plagioclase (Labradorite An₅₀₋₇₀) + Clinopyroxene (Augite) ± Olivine ± Titanomagnetite',
    typicalOccurrence: 'Oceanic crust Layer 3 (deep slow-cooling ocean floor), layered mafic intrusions (Bushveld Complex, Skaergaard, Stillwater).',
    imageUrl: 'https://images.unsplash.com/photo-1590412200988-a436970781fa?auto=format&fit=crop&w=900&q=80',
    imageCaption: 'Coarse phaneritic gabbro specimen showing interlocking dark green-black augite pyroxene and grey labradorite laths.',
    geologicalFacts: [
      'Gabbro is the plutonic intrusive equivalent of basalt, forming the deep 4–5 km thick foundation of Earth\'s oceanic crust.',
      'The Skaergaard layered intrusion in Greenland is the world\'s most famous natural laboratory for studying magma chamber fractional crystallization.',
      'The Bushveld Igneous Complex in South Africa—a titanic layered gabbro-norite intrusion—holds >75% of the world\'s platinum and chromium reserves.',
    ],
  },
  'rock-anorthosite': {
    formula: 'Plagioclase Feldspar (Labradorite/Bytownite > 90%) ± Pyroxene ± Ilmenite',
    typicalOccurrence: 'Proterozoic massif-type intrusions (Grenville Province, Rogaland Norway) and Lunar Highlands.',
    imageUrl: 'https://images.unsplash.com/photo-1567095761054-7a02e69e5c43?auto=format&fit=crop&w=900&q=80',
    imageCaption: 'Iridescent labradorite-rich anorthosite hand sample displaying bright blue-green labradorescence.',
    geologicalFacts: [
      'The pale, bright white lunar highlands visible on the Moon are composed almost entirely of ancient calcic anorthosite rock.',
      '4.5 billion years ago, as the primordial Lunar Magma Ocean cooled, low-density anorthite plagioclase floated to the top like icebergs, forming the Moon\'s crust.',
      'Many terrestrial anorthosites display vivid blue, green, and golden schiller effects (labradorescence) caused by sub-microscopic exsolution lamellae.',
    ],
  },
  'rock-diorite': {
    formula: 'Plagioclase (Andesine An₃₀₋₅₀) + Hornblende + Biotite ± Pyroxene (Quartz < 5%)',
    typicalOccurrence: 'Subduction arc roots, Andean-type continental margins, and zoning rims of granitic plutons.',
    imageUrl: 'https://images.unsplash.com/photo-1525857597365-5f6dbff2e36e?auto=format&fit=crop&w=900&q=80',
    imageCaption: 'Classic "salt-and-pepper" diorite hand sample composed of white andesine and black prismatic hornblende.',
    geologicalFacts: [
      'Its iconic speckled black-and-white appearance earned diorite the universal moniker "salt-and-pepper rock".',
      'The ancient Code of Hammurabi (one of history\'s oldest legal codes, c. 1750 BCE) was chiseled into a 2.25-meter black diorite stele.',
      'Extremely tough and weather-resistant, diorite was favored by ancient Egyptian, Mayan, and Incan stonemasons for monumental sculptures.',
    ],
  },
  'rock-syenite': {
    formula: 'Alkali Feldspar (Orthoclase/Microcline > 65%) + Plagioclase (Oligoclase) + Hornblende/Biotite (Quartz < 5%)',
    typicalOccurrence: 'Alkaline igneous provinces, intraplate continental rifts, and alkaline ring-dike complexes (Oslo Graben, Kola Peninsula).',
    imageUrl: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=900&q=80',
    imageCaption: 'Pinkish-grey syenite featuring dominant alkali feldspar crystals with hornblende and minor nepheline.',
    geologicalFacts: [
      'Named after Syene (now Aswan) in southern Egypt, though the ancient stone quarried there was actually a hornblende granite.',
      'Syenite is essentially a granite with almost all the quartz removed; it represents the plutonic equivalent of trachyte.',
      'Fluorescent sodalite-bearing syenite pebbles found along Lake Superior beaches glow fiery bright yellow under UV light (known as "Yooperlites").',
    ],
  },
  'rock-monzonite': {
    formula: 'Plagioclase (Andesine/Oligoclase 35-65%) + Alkali Feldspar (35-65%) + Pyroxene/Hornblende (Quartz < 5%)',
    typicalOccurrence: 'Intermediate subduction-zone plutons and porphyry copper-gold deposit districts (Bingham Canyon Utah, Monzoni Alps Italy).',
    imageUrl: 'https://images.unsplash.com/photo-1533038590840-1cde6e668a91?auto=format&fit=crop&w=900&q=80',
    imageCaption: 'Phaneritic monzonite hand sample showing balanced equal proportions of pinkish K-feldspar and grey plagioclase.',
    geologicalFacts: [
      'Named after the Monzoni mountain range in the Val di Fassa, Trentino, Italy.',
      'Occupies the exact center of the QAPF plutonic triangle, with approximately equal proportions of plagioclase and alkali feldspar.',
      'Quartz monzonite porphyries host several of the world\'s largest open-pit copper mines, including Bingham Canyon in Utah.',
    ],
  },

  // ==========================================
  // --- ULTRAMAFIC & MANTLE ROCKS ---
  // ==========================================
  'rock-dunite': {
    formula: 'Forsteritic Olivine (Fo₉₀₋₉₂ > 90 vol%) + Chromite ± Pyrope',
    typicalOccurrence: 'Mantle sections of ophiolite complexes (Oman Ophiolite, Troodos), alpine peridotite massifs, and lower layered intrusions.',
    imageUrl: 'https://images.unsplash.com/photo-1590412200988-a436970781fa?auto=format&fit=crop&w=900&q=80',
    imageCaption: 'Brilliant yellow-green fresh dunite specimen consisting almost entirely of interlocking forsterite olivine grains with tiny black chromite specks.',
    geologicalFacts: [
      'Consists of more than 90% olivine; fresh dunite is vivid lime-green, weathering to a characteristic rusty reddish-orange crust due to iron oxidation.',
      'Named after Dun Mountain in Nelson, New Zealand, which owes its bare, un-vegetated landscape to toxic concentrations of nickel and chromium in ultramafic soil.',
      'Industrial dunite is currently being researched as a premier rock for enhanced mineral weathering to capture atmospheric CO₂ on a gigaton scale.',
    ],
  },
  'rock-harzburgite': {
    formula: 'Olivine (Fo₉₀ > 60%) + Orthopyroxene (Enstatite 10-40%) + Chromite (Cpx < 5%)',
    typicalOccurrence: 'Sub-oceanic lithospheric mantle (abyssal peridotites), ophiolites, and Archean cratonic mantle keels.',
    imageUrl: 'https://images.unsplash.com/photo-1525857597365-5f6dbff2e36e?auto=format&fit=crop&w=900&q=80',
    imageCaption: 'Harzburgite specimen showing brown weathered enstatite bastite crystals embedded in dark green olivine matrix.',
    geologicalFacts: [
      'Represents refractory residual mantle left behind after extensive basaltic melt extraction beneath mid-ocean ridges and back-arc basins.',
      'Named after the Harz Mountains of Germany.',
      'In oceanic ophiolites, harzburgite forms the kilometers-thick mantle section directly beneath the Moho (crust-mantle boundary).',
    ],
  },
  'rock-lherzolite': {
    formula: 'Olivine (50-60%) + Orthopyroxene (20-30%) + Clinopyroxene (Chrome-Diopside 10-20%) + Spinel/Garnet',
    typicalOccurrence: 'Fertile upper mantle, orogenic peridotite massifs (Etang de Lherz Pyrenees, Ronda Spain, Beni Bousera Morocco), and mantle xenoliths.',
    imageUrl: 'https://images.unsplash.com/photo-1567095761054-7a02e69e5c43?auto=format&fit=crop&w=900&q=80',
    imageCaption: 'Lherzolite mantle rock showing emerald-green chrome-diopside crystals contrasting against olive-green olivine and bronze enstatite.',
    geologicalFacts: [
      'Represents "fertile" (un-depleted) Earth mantle capable of generating basaltic melt upon decompression melting.',
      'Named after Étang de Lhers in the French Pyrenees, the type locality where geologists first studied subcontinental mantle upwelling.',
      'Contains striking emerald-green Cr-diopside crystals that can be used by diamond exploration geologists as kimberlite indicator minerals.',
    ],
  },
  'rock-pyroxenite': {
    formula: 'Clinopyroxene (Augite/Diopside) + Orthopyroxene (Enstatite) > 60% ± Olivine ± Garnet',
    typicalOccurrence: 'Mantle veins and dikes cutting peridotite, layered mafic-ultramafic intrusions (Bushveld, Stillwater), and high-pressure xenoliths.',
    imageUrl: 'https://images.unsplash.com/photo-1533038590840-1cde6e668a91?auto=format&fit=crop&w=900&q=80',
    imageCaption: 'Dark coarse pyroxenite composed almost entirely of lustrous interlocking green and black pyroxene crystals.',
    geologicalFacts: [
      'Because pyroxenite has a lower melting point than peridotite, recycled oceanic crust pyroxenite veins melt first during mantle upwelling.',
      'Serves as a critical host rock for layered chromitite reefs and platinum group element (PGE) mineralization in layered intrusions.',
      'Can be classified as clinopyroxenite, orthopyroxenite (bronzitite), or websterite depending on pyroxene ratios.',
    ],
  },

  // ==========================================
  // --- SEDIMENTARY ROCKS ---
  // ==========================================
  'rock-paas-shale': {
    formula: 'Illite + Kaolinite + Smectite + Quartz (silt) + Iron Oxides + Organic Carbon',
    typicalOccurrence: 'Post-Archean sedimentary basins, continental shelves, deep marine mudstones, and foreland basins.',
    imageUrl: 'https://images.unsplash.com/photo-1588345921523-c2dcdb7f1dcd?auto=format&fit=crop&w=900&q=80',
    imageCaption: 'Dark grey fissile marine shale hand specimen displaying razor-thin laminae and micro-cleavage.',
    geologicalFacts: [
      'PAAS (Post-Archean Australian Shale) is an internationally recognized standard reference composite established by Taylor & McLennan (1985).',
      'Serves as the global geochemical baseline against which all sedimentary rocks, crustal weathering profiles, and REE anomalies are normalized.',
      'Fine-grained clay minerals preserve delicate fossil soft tissues through Burgess Shale-type Lagerstätte preservation.',
    ],
  },
  'rock-arkose-sandstone': {
    formula: 'Quartz (50-70%) + Feldspar (K-Feldspar/Plag > 25%) + Rock Fragments + Calcite/Clay Cement',
    typicalOccurrence: 'Alluvial fans and graben basin fills adjacent to rapidly uplifting granitic basement highlands (fault scarps, rift basins).',
    imageUrl: 'https://images.unsplash.com/photo-1525857597365-5f6dbff2e36e?auto=format&fit=crop&w=900&q=80',
    imageCaption: 'Pinkish-red arkosic sandstone hand specimen rich in angular pink orthoclase feldspar grains and quartz.',
    geologicalFacts: [
      'Because feldspar rapidly alters to clay in humid climates, the abundance of fresh feldspar (>25%) proves rapid tectonic uplift, short transport, and arid or cold climate.',
      'Uluru (Ayers Rock) in central Australia is one of the world\'s largest monoliths, consisting of steeply dipping Cambrian Mutitjulu Arkose.',
      'Characteristically pink, orange, or reddish-brown due to the presence of oxidized iron coatings on pink potassic feldspar grains.',
    ],
  },
  'rock-quartz-arenite': {
    formula: 'Monocrystalline Quartz (>95%) + Chert / Heavy Minerals (<5%) + Silica Cement',
    typicalOccurrence: 'Passive continental margins, stable cratonic platforms, and recycled desert dune fields (St. Peter Sandstone, Coconino Sandstone).',
    imageUrl: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=900&q=80',
    imageCaption: 'Pure white supermature quartz arenite hand sample composed of well-rounded, frosted quartz grains.',
    geologicalFacts: [
      'Represents the pinnacle of sedimentary textural and mineralogical maturity: all unstable minerals (feldspar, micas, ferromagnesians) have been destroyed by weathering.',
      'SiO₂ typically exceeds 98–99 wt%, making pure quartz arenites the raw material source for high-purity glass and silicon semiconductors.',
      'Grains frequently exhibit frosted, pitted surfaces produced by countless grain-to-grain impacts in ancient eolian (windblown) sand dunes.',
    ],
  },
  'rock-greywacke': {
    formula: 'Quartz + Feldspar + Lithic Rock Fragments (>15-75%) in abundant Chlorite/Clay Matrix (>15%)',
    typicalOccurrence: 'Submarine deep-sea turbidite fans, subduction trench accretionary prisms, and active continental margin basins.',
    imageUrl: 'https://images.unsplash.com/photo-1590412200988-a436970781fa?auto=format&fit=crop&w=900&q=80',
    imageCaption: 'Dark grey indurated greywacke hand specimen showing poorly sorted angular grains suspended in muddy matrix.',
    geologicalFacts: [
      'Often called "dirty sandstone" because it contains more than 15% fine-grained matrix enclosing poorly sorted, angular mineral and rock fragments.',
      'Deposited by catastrophic underwater avalanches known as turbidity currents that rush down continental slopes at speeds up to 70 km/h.',
      'Displays classical Bouma sequences with graded bedding, flute casts, and load structures on the undersides of turbidite beds.',
    ],
  },
  'rock-limestone-micrite': {
    formula: 'Calcite (CaCO₃ > 90%) ± Aragonite ± Dolomite ± Clay / Chert nodules',
    typicalOccurrence: 'Shallow warm tropical marine carbonate platforms (Bahamas, Great Barrier Reef, Mesozoic Tethys Seaway), chalk deposits.',
    imageUrl: 'https://images.unsplash.com/photo-1567095761054-7a02e69e5c43?auto=format&fit=crop&w=900&q=80',
    imageCaption: 'Fine-grained micritic limestone hand sample with fossil shell impressions and smooth conchoidal fracture.',
    geologicalFacts: [
      'The vast majority of Earth\'s limestone was formed biogenically from the skeletal remains of marine organisms (corals, foraminifera, coccolithophores).',
      'The White Cliffs of Dover in England are composed of pure microscopic coccolithophorid algal plates deposited in a Cretaceous greenhouse ocean.',
      'Limestone terrains develop dramatic karst landscapes—caves, sinkholes, and subterranean rivers—via dissolution by weak carbonic acid in rainwater.',
    ],
  },
  'rock-dolostone': {
    formula: 'Dolomite (CaMg(CO₃)₂ > 90%) ± Calcite ± Quartz ± Evaporites',
    typicalOccurrence: 'Diagenetically altered shallow marine carbonate platforms, sabkha environments, and restricted hypersaline lagoons.',
    imageUrl: 'https://images.unsplash.com/photo-1533038590840-1cde6e668a91?auto=format&fit=crop&w=900&q=80',
    imageCaption: 'Tan-grey crystalline dolostone rock featuring vuggy porosity and curved saddle-dolomite crystals.',
    geologicalFacts: [
      'Formed primarily through "dolomitization", where magnesium-rich saline groundwater replaces half the calcium ions in precursor limestone: 2CaCO₃ + Mg²⁺ → CaMg(CO₃)₂ + Ca²⁺.',
      'Dolomitization produces a ~13% volume contraction in the crystal lattice, generating intercrystalline vuggy porosity that makes dolostone a premier oil, gas, and groundwater reservoir.',
      'The jagged, pale peaks of the Dolomite Alps in northern Italy are carved out of massive Triassic dolostone reefs.',
    ],
  },
  'rock-bif': {
    formula: 'Magnetite (Fe₃O₄) + Hematite (Fe₂O₃) + Microcrystalline Chert/Jasper (SiO₂)',
    typicalOccurrence: 'Archean and Paleoproterozoic cratonic basins (Hamersley Basin Australia, Mesabi Range Minnesota, Carajás Brazil, Krivoy Rog Ukraine).',
    imageUrl: 'https://images.unsplash.com/photo-1525857597365-5f6dbff2e36e?auto=format&fit=crop&w=900&q=80',
    imageCaption: 'Stunning polished hand sample of Banded Iron Formation (BIF) displaying alternating scarlet-red jasper and metallic silver-black hematite bands.',
    geologicalFacts: [
      'Provides direct geological testimony to the "Great Oxidation Event" (2.4 to 1.8 Ga), when photosynthetic cyanobacteria first released oxygen into anoxic, iron-rich oceans.',
      'Dissolved oceanic Fe²⁺ bonded with newly released O₂, precipitating trillions of tons of insoluble iron oxides in alternating seasonal rhythm with chert.',
      'Accounts for over 90% of the world\'s commercially mined iron ore, supplying the foundation of global steel production.',
    ],
  },

  // ==========================================
  // --- METAMORPHIC ROCKS ---
  // ==========================================
  'rock-pelitic-schist': {
    formula: 'Biotite + Muscovite + Quartz + Plagioclase ± Almandine Garnet ± Staurolite ± Kyanite',
    typicalOccurrence: 'Barrovian regional metamorphic belts in mountain collision zones (Scottish Highlands, Appalachian Mountains, Alps).',
    imageUrl: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=900&q=80',
    imageCaption: 'Garnet-mica schist hand specimen featuring glistening silvery muscovite foliation wrapping around prominent red almandine porphyroblasts.',
    geologicalFacts: [
      'George Barrow in 1893 mapped the progressive metamorphic zones of the Scottish Dalradian schists, establishing the worldwide concept of metamorphic index minerals.',
      'Formed by medium-grade regional metamorphism of shale (mudstone) at temperatures of 450–600°C and pressures of 0.3–0.7 GPa.',
      'The strong planar alignment of sheet-silicate mica flakes gives schist its diagnostic wavy foliation ("schistosity"), causing it to split into lustrous plates.',
    ],
  },
  'rock-gneiss-amphibolite': {
    formula: 'Quartz + K-Feldspar + Plagioclase + Biotite + Hornblende (Compositional Banding)',
    typicalOccurrence: 'Deep continental collision roots, high-grade crystalline basements, and Precambrian cratonic shields (Lewisian Gneiss Scotland, Acasta Gneiss).',
    imageUrl: 'https://images.unsplash.com/photo-1590412200988-a436970781fa?auto=format&fit=crop&w=900&q=80',
    imageCaption: 'Orthogneiss hand specimen showing striking segregated gneissic banding: alternating light quartzo-feldspathic and dark biotite-hornblende bands.',
    geologicalFacts: [
      'The Acasta Gneiss in the Northwest Territories of Canada is the oldest known intact crustal rock on Earth, dated to ~4.03 billion years old.',
      'Gneissic banding is produced by high-temperature solid-state metamorphic segregation and ductile shear at temperatures between 600°C and 800°C.',
      'Can form from either an igneous protolith ("orthogneiss", e.g. deformed granite) or a sedimentary protolith ("paragneiss", e.g. metamorphosed greywacke).',
    ],
  },
  'rock-amphibolite': {
    formula: 'Hornblende (50-70%) + Plagioclase (Andesine/Labradorite 30-50%) ± Quartz ± Epidote ± Garnet',
    typicalOccurrence: 'Medium to high-grade regional metamorphic terranes; formed by metamorphism of basalt, gabbro, or marl.',
    imageUrl: 'https://images.unsplash.com/photo-1567095761054-7a02e69e5c43?auto=format&fit=crop&w=900&q=80',
    imageCaption: 'Dark green to black amphibolite hand specimen showing lineated prismatic hornblende needles and white plagioclase.',
    geologicalFacts: [
      'Defines the iconic "Amphibolite Facies" of regional metamorphism (temperatures 500–750°C), representing mid-crustal depth conditions.',
      'Derived through the hydration and recrystallization of mafic igneous rocks (basalts and gabbros) as hydrous fluids infiltrate during collision.',
      'Linear alignment of black hornblende needles creates a distinct metamorphic lineation, recording the direction of tectonic stretching.',
    ],
  },
  'rock-eclogite': {
    formula: 'Omphacite (Na-Clinopyroxene) + Pyrope-Almandine Garnet ± Kyanite ± Rutile ± Coesite',
    typicalOccurrence: 'Ultra-high-pressure (UHP) subduction zones and deep subducted oceanic slabs (Dabie-Sulu China, Western Gneiss Region Norway, Zermatt-Saas Alps).',
    imageUrl: 'https://images.unsplash.com/photo-1588345921523-c2dcdb7f1dcd?auto=format&fit=crop&w=900&q=80',
    imageCaption: 'Vibrant "Christmas tree rock" eclogite hand specimen displaying ruby-red pyrope garnets embedded in an emerald-green omphacite groundmass.',
    geologicalFacts: [
      'Affectionately nicknamed the "Christmas tree rock" by petrologists due to its striking contrast of red garnets and green omphacite pyroxene.',
      'Forms under extreme ultra-high-pressure (UHP) conditions (>1.5 to 3.0 GPa) when cold oceanic basaltic crust is subducted to depths of 50 to 120+ km.',
      'Eclogite has an exceptionally high density (~3.4–3.6 g/cm³), significantly denser than surrounding mantle peridotite, making it the primary driver of slab pull.',
    ],
  },
  'rock-blueschist': {
    formula: 'Glaucophane (Sodic Amphibole) + Lawsonite + Jadeite + Aragonite ± Chlorite ± Epidote',
    typicalOccurrence: 'Subduction zone accretionary complexes and paleosubduction trenches (Franciscan Complex California, Cyclades Greece, Sesia Zone Alps).',
    imageUrl: 'https://images.unsplash.com/photo-1525857597365-5f6dbff2e36e?auto=format&fit=crop&w=900&q=80',
    imageCaption: 'Striking indigo-blue blueschist hand sample containing fibrous glaucophane amphibole and pale lawsonite.',
    geologicalFacts: [
      'Characterized by high-pressure, low-temperature (HP-LT) metamorphic conditions (P = 0.6–1.2 GPa, T = 200–400°C), diagnostic of subduction zones.',
      'Owes its vivid violet-blue color to glaucophane, a sodic amphibole that only crystallizes where crust is forced rapidly downward into the cold trench.',
      'The discovery of blueschist in the Franciscan Complex of California was one of the pivotal pieces of geological evidence proving plate tectonic subduction.',
    ],
  },
  'rock-granulite': {
    formula: 'Plagioclase + Orthopyroxene (Hypersthene) + Clinopyroxene + Garnet ± Quartz (Anhydrous)',
    typicalOccurrence: 'Deep lower continental crust (25-45 km depth), ancient shield roots, and exhumed collision cores (Kola Peninsula, Limpopo Belt, Adirondacks).',
    imageUrl: 'https://images.unsplash.com/photo-1533038590840-1cde6e668a91?auto=format&fit=crop&w=900&q=80',
    imageCaption: 'Dense granulite hand specimen featuring granoblastic texture with brown orthopyroxene, quartz, and garnet.',
    geologicalFacts: [
      'Represents high-temperature (>750–900°C) metamorphic conditions in the lower continental crust where hydrous minerals like mica and amphibole breakdown.',
      'Has a diagnostic granoblastic "sugary" texture of interlocking equidimensional mineral grains, often containing hypersthene (orthopyroxene).',
      'Extremely depleted in water and radioactive heat-producing elements (U, Th, K), which were stripped away during peak metamorphism and melt extraction.',
    ],
  },
  'rock-quartzite': {
    formula: 'Recrystallized Quartz (SiO₂ > 98%) ± Sericite ± Zircon ± Rutile',
    typicalOccurrence: 'Metamorphosed quartz sandstone sequences in fold-and-thrust belts (Appalachian Valley & Ridge, Scandinavian Caledonides).',
    imageUrl: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=900&q=80',
    imageCaption: 'Glassy, extremely hard white quartzite hand specimen displaying clean conchoidal fracture slicing across quartz grains.',
    geologicalFacts: [
      'Unlike sandstone where a hammer blows breaks the cement around individual sand grains, in quartzite metamorphic recrystallization welds grains together so fractures shear directly through them.',
      'Consists of almost 99% quartz and is so chemically and mechanically indestructible that it forms prominent linear mountain ridges and resistant hogsbacks.',
      'Mohs hardness of 7; resists scratching by steel knives or glass, making it one of Earth\'s toughest common rocks.',
    ],
  },
  'rock-marble': {
    formula: 'Recrystallized Calcite / Dolomite (CaCO₃ / CaMg(CO₃)₂ > 95%) ± Tremolite ± Diopside',
    typicalOccurrence: 'Contact and regional metamorphic belts where limestone or dolostone was subjected to heat and pressure (Carrara Italy, Vermont, Pentelikon Greece).',
    imageUrl: 'https://images.unsplash.com/photo-1567095761054-7a02e69e5c43?auto=format&fit=crop&w=900&q=80',
    imageCaption: 'Pure white crystalline Carrara marble hand specimen displaying interlocking sugary saccharoidal calcite cleavage faces.',
    geologicalFacts: [
      'The iconic white statuary marble of Carrara in Tuscany was chosen by Michelangelo to carve his masterpieces *David* and the *Pietà*.',
      'The Parthenon in Athens was constructed from Pentelic marble quarried from Mount Pentelikon in the 5th century BCE.',
      'The swirling colored "veins" in ornamental marble represent metamorphism of minor clay, silt, or chert impurities in the original limestone reef.',
    ],
  },

  // ==========================================
  // --- MINERALS ---
  // ==========================================
  'min-forsterite': {
    formula: 'Mg₂SiO₄',
    typicalOccurrence: 'Mantle peridotites (dunites, lherzolites), primitive basalt phenocrysts, kimberlite xenoliths, and stony-iron pallasite meteorites.',
    imageUrl: 'https://images.unsplash.com/photo-1590412200988-a436970781fa?auto=format&fit=crop&w=900&q=80',
    imageCaption: 'Vivid olive-green gemmy forsterite (peridot) crystal cluster embedded in vesicular basalt matrix.',
    geologicalFacts: [
      'Gem-quality forsterite is known as peridot—one of the few gemstones (along with diamond) formed deep in Earth\'s mantle rather than the continental crust.',
      'Peridot crystals are found embedded in space meteorites (pallasites), creating extraterrestrial jewelry billions of years old.',
      'Makes up roughly 50% of Earth\'s upper mantle down to 410 km depth, where extreme pressure triggers its transformation into wadsleyite.',
    ],
  },
  'min-chrysolite-ol': {
    formula: '(Mg₀.₈Fe₀.₂)₂SiO₄',
    typicalOccurrence: 'Ubiquitous phenocrysts in mid-ocean ridge basalts, ocean island basalts, continental flood basalts, and layered gabbroic intrusions.',
    imageUrl: 'https://images.unsplash.com/photo-1533038590840-1cde6e668a91?auto=format&fit=crop&w=900&q=80',
    imageCaption: 'Aggregate of vitreous green chrysolite olivine grains extracted from a volcanic basalt bomb.',
    geologicalFacts: [
      'Represents the classic Fo80 composition predicted by Bowen\'s Reaction Series as the first silicate mineral to crystallize from cooling basaltic magma.',
      'Green sand beaches on Earth (such as Papakōlea Beach in Hawaii) are created when ocean waves wash away lighter volcanic glass, concentrating heavy olivine.',
      'Rapidly alters to serpentine, iddingsite, and iron oxides when exposed to rain and groundwater at Earth\'s surface.',
    ],
  },
  'min-fayalite': {
    formula: 'Fe₂SiO₄',
    typicalOccurrence: 'Iron-rich felsic igneous rocks (fayalite granites, quartz syenites, ferrogabbros) and metamorphosed banded iron formations.',
    imageUrl: 'https://images.unsplash.com/photo-1525857597365-5f6dbff2e36e?auto=format&fit=crop&w=900&q=80',
    imageCaption: 'Dark brownish-black, lustrous crystalline mass of fayalite from an iron-rich granite.',
    geologicalFacts: [
      'The pure iron endmember of the olivine series; named after Faial Island in the Azores where it was first described.',
      'Because of its high iron content, its specific gravity (4.39 g/cm³) is substantially greater than forsterite (3.27 g/cm³).',
      'Can coexist in equilibrium with free quartz, unlike magnesium-rich olivine which reacts with quartz to form enstatite.',
    ],
  },
  'min-diopside': {
    formula: 'CaMgSi₂O₆',
    typicalOccurrence: 'Upper mantle lherzolites (Cr-diopside), calc-silicate skarns, metamorphosed dolomitic limestones, and kimberlite pipes.',
    imageUrl: 'https://images.unsplash.com/photo-1567095761054-7a02e69e5c43?auto=format&fit=crop&w=900&q=80',
    imageCaption: 'Brilliant emerald-green chrome-diopside crystal exhibiting monoclinic prismatic form and vitreous luster.',
    geologicalFacts: [
      'Chrome diopside contains trace chromium (Cr³⁺) that gives it an intense, vibrant emerald-green color prized in fine gemstone jewelry.',
      'Exploration geologists use bright green Cr-diopside as a primary indicator mineral when searching for diamond-bearing kimberlite pipes.',
      'Has two distinct cleavage planes intersecting at approximately 87° and 93°, diagnostic of all clinopyroxenes.',
    ],
  },
  'min-augite': {
    formula: '(Ca,Na)(Mg,Fe,Al,Ti)(Si,Al)₂O₆',
    typicalOccurrence: 'The most abundant clinopyroxene on Earth; forms phenocrysts and groundmass in basalts, gabbros, andesites, and lunar rocks.',
    imageUrl: 'https://images.unsplash.com/photo-1525857597365-5f6dbff2e36e?auto=format&fit=crop&w=900&q=80',
    imageCaption: 'Short prismatic black-green lustrous augite crystal embedded in weathered volcanic matrix.',
    geologicalFacts: [
      'Name comes from the Greek "auge" (αὐγή), meaning "luster" or "shine", in reference to the sparkling cleavage faces of its crystals.',
      'Titanium-rich varieties ("titanaugite") found in alkali basalts exhibit striking hourglass and sector zoning under cross-polarized light.',
      'One of the principal mineral components of the lunar basalt samples brought back to Earth by the Apollo missions.',
    ],
  },
  'min-hedenbergite': {
    formula: 'CaFeSi₂O₆',
    typicalOccurrence: 'Contact metamorphic skarns, metasomatized iron-rich formations, and late-stage differentiate in alkaline igneous plutons.',
    imageUrl: 'https://images.unsplash.com/photo-1590412200988-a436970781fa?auto=format&fit=crop&w=900&q=80',
    imageCaption: 'Dark green to black radiating fibrous crystal bundle of hedenbergite from a contact skarn.',
    geologicalFacts: [
      'Forms a complete solid-solution series with diopside; hedenbergite represents the iron-rich endmember.',
      'Named after the Swedish chemist and mineralogist Ludwig Hedenberg (1766–1800).',
      'Frequently forms dramatic radiating prismatic crystal fans associated with green andradite garnet in ore-bearing skarns.',
    ],
  },
  'min-enstatite': {
    formula: 'Mg₂Si₂O₆',
    typicalOccurrence: 'Major component of mantle harzburgites, norites, bronzitites, high-grade granulites, and stony chondrite meteorites.',
    imageUrl: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=900&q=80',
    imageCaption: 'Submetallic brownish-green enstatite (bronzite) cleavage mass showing characteristic bronze chatoyancy.',
    geologicalFacts: [
      'Named from the Greek "enstates" (opponent), referring to its exceptional resistance to melting before a blowpipe flame.',
      'Enstatite chondrites are rare meteorites whose isotopic oxygen composition is virtually identical to Earth, suggesting they represent the primary building blocks of our planet.',
      'The intermediate variety bronzite displays a distinctive metallic sub-bronzy luster caused by microscopic oriented iron oxide exsolution needles.',
    ],
  },
  'min-hypersthene': {
    formula: '(Mg,Fe)₂Si₂O₆',
    typicalOccurrence: 'Norites, charnockites, andesite lavas, deep granulite facies metamorphic rocks, and lunar crust.',
    imageUrl: 'https://images.unsplash.com/photo-1533038590840-1cde6e668a91?auto=format&fit=crop&w=900&q=80',
    imageCaption: 'Brownish-black hypersthene orthopyroxene specimen with prominent pinacoidal cleavage.',
    geologicalFacts: [
      'Name translates from Greek as "over-strength" or "hyper-strong" because its hardness exceeds that of hornblende amphibole.',
      'Famous in optical mineralogy for displaying vivid pleochroism under plane-polarized light, shifting from pale green to salmon-pink.',
      'Characteristic index mineral of high-grade granulite facies rocks and charnockitic deep-crustal plutons.',
    ],
  },
  'min-jadeite': {
    formula: 'NaAlSi₂O₆',
    typicalOccurrence: 'High-pressure metamorphic serpentinite mélanges along ancient subduction zones (Myanmar, Guatemala, Japan, California).',
    imageUrl: 'https://images.unsplash.com/photo-1567095761054-7a02e69e5c43?auto=format&fit=crop&w=900&q=80',
    imageCaption: 'Polished pebble of emerald-green imperial jadeite exhibiting intense color and fine interlocking microcrystalline grain.',
    geologicalFacts: [
      'Jadeite is the premier, rare mineral that constitutes true "Jade" (distinct from the amphibole nephrite); Myanmar produces >90% of the world\'s gem-quality jadeite.',
      'Formed exclusively under high pressure and low temperature conditions during ocean-floor subduction: albite → jadeite + quartz.',
      'Prized by Mesoamerican Olmec and Maya civilizations for ceremonial scepters, ritual masks, and royal funerary ornaments.',
    ],
  },
  'min-aegirine': {
    formula: 'NaFe³⁺Si₂O₆',
    typicalOccurrence: 'Alkaline igneous rocks (nepheline syenites, carbonatites, phonolites) and sodic peralkaline granites (pantellerites).',
    imageUrl: 'https://images.unsplash.com/photo-1525857597365-5f6dbff2e36e?auto=format&fit=crop&w=900&q=80',
    imageCaption: 'Long, slender, dark green to black lustrous prismatic aegirine crystals on white feldspar matrix.',
    geologicalFacts: [
      'Named after Ægir, the Norse god of the stormy sea, because the type specimens were found on the rocky coasts of southern Norway.',
      'Forms striking elongated prismatic needle-like crystals with sharp, steep terminations and brilliant glass-like luster.',
      'The sodium and ferric iron content records high oxygen fugacity and extreme alkali enrichment in magma conduits.',
    ],
  },
  'min-omphacite': {
    formula: '(Ca,Na)(Mg,Fe²⁺,Fe³⁺,Al)Si₂O₆',
    typicalOccurrence: 'Essential diagnostic clinopyroxene of ultra-high-pressure eclogite rocks formed in subducted oceanic crust (40-120 km depth).',
    imageUrl: 'https://images.unsplash.com/photo-1588345921523-c2dcdb7f1dcd?auto=format&fit=crop&w=900&q=80',
    imageCaption: 'Emerald-green granular omphacite clinopyroxene in an eclogite hand specimen alongside red pyrope garnets.',
    geologicalFacts: [
      'Name comes from the Greek "omphax" (ὄμφαξ), meaning "unripe grape", reflecting its characteristic grass-green to olive-green hue.',
      'Forms a complex intermediate solid solution between diopside and jadeite, stable only at high subduction pressures.',
      'At pressures above 2.5 GPa, omphacite can incorporate excess silica into its crystal lattice, transforming into high-pressure majoritic clinopyroxene.',
    ],
  },
  'min-tremolite': {
    formula: 'Ca₂Mg₅Si₈O₂₂(OH)₂',
    typicalOccurrence: 'Contact and regional metamorphosed dolomitic limestones, talc schists, and ultramafic serpentinites.',
    imageUrl: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=900&q=80',
    imageCaption: 'Bladed, glistening white to pale-green prismatic crystal cluster of tremolite from a dolomitic marble.',
    geologicalFacts: [
      'Named after the Val Tremola in the St. Gotthard region of the Swiss Alps where it was discovered.',
      'Forms a continuous solid-solution series with actinolite and ferro-actinolite as magnesium is replaced by iron.',
      'The fine, felted microcrystalline variety of tremolite/actinolite forms nephrite jade, revered in Chinese culture for over 5,000 years.',
    ],
  },
  'min-hornblende': {
    formula: '(Ca,Na)₂₋₃(Mg,Fe²⁺,Fe³⁺,Al)₅(Al,Si)₈O₂₂(OH)₂',
    typicalOccurrence: 'Ubiquitous in intermediate and felsic igneous rocks (andesite, dacite, diorite, granodiorite) and metamorphic amphibolites.',
    imageUrl: 'https://images.unsplash.com/photo-1590412200988-a436970781fa?auto=format&fit=crop&w=900&q=80',
    imageCaption: 'Jet-black monoclinic hornblende crystals showing diamond-shaped cross-sections with 56°/124° cleavage angles.',
    geologicalFacts: [
      'Name derives from the German "Horn" (horn) and "blenden" (to blind/deceive), because miners confused it with valuable metal ore minerals.',
      'Amphiboles like hornblende possess double-chain silicate structures with diagnostic cleavage planes intersecting at 56° and 124°.',
      'Holds 1–2 wt% structural water as (OH)⁻ groups, making it a critical geochemical carrier of subducted slab water into the deep continental crust.',
    ],
  },
  'min-glaucophane': {
    formula: 'Na₂Mg₃Al₂Si₈O₂₂(OH)₂',
    typicalOccurrence: 'Diagnostic mineral of blueschist metamorphic facies in subduction complexes (California Coast Ranges, Cyclades, Corsica, Japan).',
    imageUrl: 'https://images.unsplash.com/photo-1525857597365-5f6dbff2e36e?auto=format&fit=crop&w=900&q=80',
    imageCaption: 'Intense lavender-blue fibrous glaucophane needles forming a dense blueschist metamorphic rock.',
    geologicalFacts: [
      'Name is derived from the Greek "glaukos" (γλαυκός, blue-gray) and "phainesthai" (to appear), due to its vivid indigo-blue coloration.',
      'Direct index mineral for high-pressure, low-temperature (HP-LT) subduction metamorphism, requiring pressures >0.7 GPa while temperatures stay cool (<400°C).',
      'Under the polarizing petrographic microscope, glaucophane displays exquisite pleochroism: blue-violet to lavender-indigo to pale yellow.',
    ],
  },
  'min-albite': {
    formula: 'NaAlSi₃O₈',
    typicalOccurrence: 'Granitic pegmatites, low-grade greenschist facies metamorphic rocks, spilites, and felsic volcanic rocks.',
    imageUrl: 'https://images.unsplash.com/photo-1567095761054-7a02e69e5c43?auto=format&fit=crop&w=900&q=80',
    imageCaption: 'Pristine white bladed cleavelandite albite crystals associated with quartz in a granitic pegmatite pocket.',
    geologicalFacts: [
      'The pure sodium endmember of the plagioclase feldspar series (Ab₉₀₋₁₀₀); name comes from the Latin "albus" (white).',
      'The platy, bladed variety known as "cleavelandite" forms open rosettes of delicate white crystals in gem-bearing pegmatites.',
      'Under the petrographic microscope, albite displays sharp, multiple polysynthetic polysynthetic twinning lamellae ("albite twinning").',
    ],
  },
  'min-oligoclase': {
    formula: '(Na₀.₈Ca₀.₂)Al₁.₂Si₂.₈O₈ (An₁₀₋₃₀)',
    typicalOccurrence: 'Common plagioclase in granites, granodiorites, tonalites, dacites, and high-grade gneisses.',
    imageUrl: 'https://images.unsplash.com/photo-1533038590840-1cde6e668a91?auto=format&fit=crop&w=900&q=80',
    imageCaption: 'Translucent oligoclase feldspar cleavage fragment showing vitreous luster and polysynthetic twin striations.',
    geologicalFacts: [
      'Name comes from the Greek "oligos" (little) and "klasis" (breaking), because its cleavage angle was thought to deviate slightly from 90°.',
      'The gem variety "sunstone" contains oriented microscopic inclusions of hematite or copper platelets that produce a dazzling golden flash (aventurescence).',
      'Intermediate plagioclase (An20) defining the transition from sodic to calcic feldspars in continental magmatic arcs.',
    ],
  },
  'min-andesine': {
    formula: '(Na₀.₆Ca₀.₄)Al₁.₄Si₂.₆O₈ (An₃₀₋₅₀)',
    typicalOccurrence: 'Characteristic plagioclase of intermediate volcanic and plutonic rocks (andesite, diorite, dacite).',
    imageUrl: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=900&q=80',
    imageCaption: 'White andesine plagioclase phenocrysts embedded in dark grey andesite volcanic lava.',
    geologicalFacts: [
      'First described in 1841 from lavas in the Andes Mountains of Colombia, from which it takes its name.',
      'Commonly forms oscillating growth zones in volcanic phenocrysts, recording thermal and chemical pulses inside magma chambers prior to eruption.',
      'Also occurs in massif-type anorthosites and granulite-facies metamorphic basements.',
    ],
  },
  'min-labradorite': {
    formula: '(Ca₀.₆Na₀.₄)Al₁.₆Si₂.₄O₈ (An₅₀₋₇₀)',
    typicalOccurrence: 'Basalts, gabbros, anorthosites (Paul\'s Island Labrador), troctolites, and lunar basalts.',
    imageUrl: 'https://images.unsplash.com/photo-1525857597365-5f6dbff2e36e?auto=format&fit=crop&w=900&q=80',
    imageCaption: 'Polished slab of labradorite showcasing breathtaking iridescent electric blue and peacock-green labradorescence.',
    geologicalFacts: [
      'Famous worldwide for "labradorescence"—an optical interference effect that flashes metallic electric blue, violet, green, and gold when tilted to light.',
      'The iridescence is caused by light diffraction between microscopic exsolution lamellae of alternating Bøggild miscibility gap feldspars.',
      'First recognized in 1770 on Paul\'s Island near the town of Nain in Labrador, Canada, by Moravian missionaries.',
    ],
  },
  'min-bytownite': {
    formula: '(Ca₀.₈Na₀.₂)Al₁.₈Si₂.₂O₈ (An₇₀₋₉₀)',
    typicalOccurrence: 'Primitive basaltic lavas, layered gabbros, eucrite achondrite meteorites, and lunar highlands.',
    imageUrl: 'https://images.unsplash.com/photo-1590412200988-a436970781fa?auto=format&fit=crop&w=900&q=80',
    imageCaption: 'Pale yellow to clear bytownite crystal fragment showing vitreous luster and calcic feldspar composition.',
    geologicalFacts: [
      'Named after Bytown (the historic 19th-century name for Ottawa, Canada), where it was first identified.',
      'Common in primitive high-calcium mafic magmas and basaltic meteorites from asteroid 4 Vesta (eucrites).',
      'Has a higher density (~2.72 g/cm³) and refractive index than sodic plagioclases due to dense Ca²⁺ packing in the tetrahedral framework.',
    ],
  },
  'min-anorthite': {
    formula: 'CaAl₂Si₂O₈ (An₉₀₋₁₀₀)',
    typicalOccurrence: 'Contact metamorphic skarns, layered mafic complexes, ultra-calcic volcanic rocks, and Lunar Highland anorthosites.',
    imageUrl: 'https://images.unsplash.com/photo-1567095761054-7a02e69e5c43?auto=format&fit=crop&w=900&q=80',
    imageCaption: 'White crystalline anorthite crystals embedded in volcanic ejecta from Mount Vesuvius, Italy.',
    geologicalFacts: [
      'The pure calcium endmember of plagioclase; forms the primary constituent (>95%) of the ancient lunar crust returned by Apollo astronauts.',
      'Has a very high melting temperature (~1,553°C), crystallizing early from hot, anhydrous primitive magmas.',
      'Named from the Greek "an-orthos" (not straight), referring to its oblique triclinic crystal angles.',
    ],
  },
  'min-orthoclase': {
    formula: 'KAlSi₃O₈',
    typicalOccurrence: 'Granites, syenites, granitic pegmatites, and high-grade gneisses; ubiquitous rock-forming tectosilicate.',
    imageUrl: 'https://images.unsplash.com/photo-1533038590840-1cde6e668a91?auto=format&fit=crop&w=900&q=80',
    imageCaption: 'Salmon-pink prismatic orthoclase feldspar crystal displaying Carlsbad contact twinning on white quartz matrix.',
    geologicalFacts: [
      'Orthoclase defines hardness 6 on the internationally standard Mohs Hardness Scale.',
      'Its name translates from Greek as "straight fracture", because its two major cleavage planes meet at exactly 90° (unlike plagioclase).',
      'The shimmering gemstone "moonstone" is a variety of orthoclase with nanoscale albite exsolution lamellae that produce a ghostly bluish-white adularescence.',
    ],
  },
  'min-sanidine': {
    formula: '(K,Na)AlSi₃O₈',
    typicalOccurrence: 'High-temperature volcanic felsic lavas (rhyolite, trachyte, phonolite) and rapidly quenched ignimbrite tuffs.',
    imageUrl: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=900&q=80',
    imageCaption: 'Glassy, transparent sanidine crystals displaying tabular monoclinic form in volcanic rhyolite.',
    geologicalFacts: [
      'Sanidine represents the high-temperature disordered structural polymorph of potassium feldspar, where Al and Si ions are randomly distributed in the lattice.',
      'Because it quenches rapidly in explosive volcanic eruptions, sanidine preserves high-temperature crystal symmetry down to room temperature.',
      'One of the most reliable minerals for high-precision ⁴⁰Ar/³⁹Ar radiometric dating of volcanic ash beds in evolutionary anthropology and paleontological layers.',
    ],
  },
  'min-microcline': {
    formula: 'KAlSi₃O₈',
    typicalOccurrence: 'Deep slow-cooling granitic batholiths, granitic pegmatites, and high-grade metamorphic rocks.',
    imageUrl: 'https://images.unsplash.com/photo-1525857597365-5f6dbff2e36e?auto=format&fit=crop&w=900&q=80',
    imageCaption: 'Vivid blue-green amazonite microcline crystal cluster with smoky quartz from the Pikes Peak batholith.',
    geologicalFacts: [
      'Microcline is the low-temperature, fully ordered triclinic polymorph of potassium feldspar.',
      'Displays the iconic "tartan" or "gridiron" cross-hatched twinning pattern under the petrographic microscope—an unmistakable fingerprint for petrologists.',
      'The stunning turquoise-green gemstone variety "amazonite" owes its color to trace lead (Pb) substituting into the crystal lattice alongside structural water.',
    ],
  },
  'min-nepheline': {
    formula: '(Na,K)AlSiO₄',
    typicalOccurrence: 'Silica-undersaturated alkaline igneous rocks (nepheline syenites, phonolites, foidites, urtites).',
    imageUrl: 'https://images.unsplash.com/photo-1588345921523-c2dcdb7f1dcd?auto=format&fit=crop&w=900&q=80',
    imageCaption: 'Greyish-white greasy-lustered mass of nepheline associated with black aegirine in nepheline syenite.',
    geologicalFacts: [
      'Nepheline is a feldspathoid—it can never coexist in thermodynamic equilibrium with quartz; adding silica turns nepheline into albite feldspar.',
      'Name comes from the Greek "nephele" (cloud), because crystal fragments become cloudy and gelatinize when immersed in hydrochloric acid.',
      'Possesses a greasy luster on fracture surfaces, giving it the old historic German name "Fettstein" (fat stone).',
    ],
  },
  'min-leucite': {
    formula: 'KAlSi₂O₆',
    typicalOccurrence: 'Potassium-rich, silica-undersaturated volcanic lavas (Vesuvius, Phlegraean Fields, Leucite Hills Wyoming, Roman Magmatic Province).',
    imageUrl: 'https://images.unsplash.com/photo-1590412200988-a436970781fa?auto=format&fit=crop&w=900&q=80',
    imageCaption: 'Trapezohedral white-grey leucite crystals embedded in dark volcanic lava from Mount Vesuvius.',
    geologicalFacts: [
      'Crystallizes at high temperatures in the isometric crystal system as distinctive 24-faced trapezohedrons (icositetrahedrons).',
      'Mount Vesuvius ejecta and Roman volcanic lavas are world-famous for yielding pristine, sharp leucite crystals up to several centimeters across.',
      'Upon cooling below 605°C, it inverts to tetragonal symmetry while retaining the outward isometric crystal form (paramorph).',
    ],
  },
  'min-sodalite': {
    formula: 'Na₈(Al₆Si₆O₂₄)Cl₂',
    typicalOccurrence: 'Alkaline igneous rocks, nepheline syenite pegmatites, metasomatized skarns (Bancroft Ontario, Greenland, Kola Peninsula).',
    imageUrl: 'https://images.unsplash.com/photo-1567095761054-7a02e69e5c43?auto=format&fit=crop&w=900&q=80',
    imageCaption: 'Rich royal-blue sodalite rock specimen with white calcite veins from Bancroft, Ontario.',
    geologicalFacts: [
      'Named for its high sodium content; celebrated for its deep royal-blue color used in ornamental carvings and architecture.',
      'The hackmanite variety exhibits tenebrescence (reversible photochromism): when exposed to UV light, it turns raspberry-pink, fading back to white in sunlight.',
      'Fluoresces bright fiery orange-yellow under longwave ultraviolet radiation.',
    ],
  },
  'min-quartz': {
    formula: 'SiO₂',
    typicalOccurrence: 'Everywhere: granites, rhyolites, pegmatites, sandstones, hydrothermal veins, and metamorphic quartzites.',
    imageUrl: 'https://images.unsplash.com/photo-1533038590840-1cde6e668a91?auto=format&fit=crop&w=900&q=80',
    imageCaption: 'Magnificent cluster of hexagonal prismatic quartz crystals with transparent terminations and glassy luster.',
    geologicalFacts: [
      'Defines hardness 7 on the Mohs scale; the second most abundant mineral in Earth\'s continental crust after feldspar.',
      'Exhibits piezoelectricity—when mechanical pressure is applied, it generates an electric charge; this property powers billions of quartz clocks and electronic devices.',
      'Occurs in famous colored gem varieties: amethyst (purple from Fe³⁺ + irradiation), citrine (golden yellow), rose quartz (pink), and smoky quartz (gray/brown).',
    ],
  },
  'min-cristobalite': {
    formula: 'SiO₂ (High-T Polymorph)',
    typicalOccurrence: 'Spherulitic cavities in volcanic rocks (obsidian, rhyolite, andesite) and silica bricks used in industrial furnaces.',
    imageUrl: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=900&q=80',
    imageCaption: 'White spherical cristobalite "snowflakes" embedded in dark black snowflake obsidian.',
    geologicalFacts: [
      'Named after the Cerro San Cristóbal in Pachuca, Hidalgo, Mexico.',
      'Forms the white radiating starburst "snowflakes" in the popular gemstone snowflake obsidian.',
      'High-temperature polymorph of quartz stable above 1,470°C at 1 atmosphere, preserved metastably when volcanic glass rapidly cools.',
    ],
  },
  'min-pyrope': {
    formula: 'Mg₃Al₂(SiO₄)₃',
    typicalOccurrence: 'Mantle peridotites, kimberlite diamond pipes, and ultra-high-pressure eclogites.',
    imageUrl: 'https://images.unsplash.com/photo-1525857597365-5f6dbff2e36e?auto=format&fit=crop&w=900&q=80',
    imageCaption: 'Blood-red dodecahedral pyrope garnet crystal embedded in serpentinized mantle peridotite.',
    geologicalFacts: [
      'Name comes from the Greek "pyropos" (fire-eyed), celebrating its fiery crimson-red color.',
      'Famous "Bohemian garnets" mined in the Czech Republic since the Victorian era are deep red gem-quality pyrope crystals.',
      'A primary mantle-derived mineral used as a pathfinder indicator when prospecting for diamondiferous kimberlite pipes.',
    ],
  },
  'min-almandine': {
    formula: 'Fe₃Al₂(SiO₄)₃',
    typicalOccurrence: 'Regional metamorphic schists and gneisses (Barrovian garnet zone), granitic pegmatites, and alluvial placers.',
    imageUrl: 'https://images.unsplash.com/photo-1590412200988-a436970781fa?auto=format&fit=crop&w=900&q=80',
    imageCaption: 'Sharp rhombic dodecahedral wine-red almandine garnet porphyroblast perched on silvery mica schist.',
    geologicalFacts: [
      'The most common garnet species on Earth, forming classic 12-sided rhombic dodecahedron or 24-sided trapezohedron crystals.',
      'Named after Alabanda, an ancient gemstone cutting center in Asia Minor (modern Turkey).',
      'Used extensively in industry as a non-toxic, chemically inert high-pressure waterjet cutting abrasive and sandblasting medium.',
    ],
  },
  'min-spessartine': {
    formula: 'Mn₃Al₂(SiO₄)₃',
    typicalOccurrence: 'Granitic pegmatites, rhyolitic lithophysae, and manganese-rich contact metamorphic skarns.',
    imageUrl: 'https://images.unsplash.com/photo-1567095761054-7a02e69e5c43?auto=format&fit=crop&w=900&q=80',
    imageCaption: 'Brilliant mandarin-orange spessartine garnet crystals associated with smoky quartz from a granitic pegmatite.',
    geologicalFacts: [
      'Prized by gemstone connoisseurs for its electric fiery orange hue, commercially known as "Mandarin garnet".',
      'Named after the Spessart Mountains in Bavaria, Germany, where it was originally discovered.',
      'Often forms in gas cavities (lithophysae) within rhyolite lavas, where fluorine-rich vapors crystallize gem crystals.',
    ],
  },
  'min-grossular': {
    formula: 'Ca₃Al₂(SiO₄)₃',
    typicalOccurrence: 'Contact metamorphic skarns, thermally altered calc-silicate rocks, and rodingites (altered gabbros in serpentinite).',
    imageUrl: 'https://images.unsplash.com/photo-1533038590840-1cde6e668a91?auto=format&fit=crop&w=900&q=80',
    imageCaption: 'Vivid green tsavorite grossular garnet dodecahedrons on marble matrix.',
    geologicalFacts: [
      'Named after the Latin botanical name for gooseberry (*Ribes grossularia*), in reference to the green color of the original Siberian crystals.',
      'The emerald-green gem variety "tsavorite" (discovered in Kenya\'s Tsavo National Park) is colored by vanadium and rivals emerald in beauty.',
      'The cinnamon-brown variety "hessonite" has been treasured since antiquity in Sri Lanka and India as an astrological talisman.',
    ],
  },
  'min-andradite': {
    formula: 'Ca₃Fe₂³⁺(SiO₄)₃',
    typicalOccurrence: 'Contact metamorphic skarns, serpentinites, and alkaline igneous intrusions.',
    imageUrl: 'https://images.unsplash.com/photo-1588345921523-c2dcdb7f1dcd?auto=format&fit=crop&w=900&q=80',
    imageCaption: 'Lustrous black melanite andradite crystals on volcanic matrix.',
    geologicalFacts: [
      'The green variety "demantoid" (meaning "diamond-like") has a dispersion of light (0.057) higher than that of diamond (0.044), giving it extraordinary fire.',
      'Russian Tsar Peter Carl Fabergé famously favored Uralian demantoid garnets for his imperial imperial jewelry creations.',
      'The opaque black variety "melanite" was widely used in Victorian mourning jewelry.',
    ],
  },
  'min-muscovite': {
    formula: 'KAl₂(AlSi₃O₁₀)(OH)₂',
    typicalOccurrence: 'Granites, granitic pegmatites, mica schists, phyllites, and detrital grains in clastic sediments.',
    imageUrl: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=900&q=80',
    imageCaption: 'Large, translucent silvery book of muscovite mica showing perfect basal cleavage splitting into paper-thin sheets.',
    geologicalFacts: [
      'In medieval Russia, huge sheets of transparent muscovite were used as windowpanes ("Muscovy glass") because glass was rare and brittle.',
      'Has perfect {001} basal cleavage, allowing it to be cleaved into flexible, elastic sheets thinner than a wavelength of light.',
      'Possesses supreme electrical insulating strength and thermal stability, widely used in high-voltage electronic capacitors and furnace sight-glasses.',
    ],
  },
  'min-biotite': {
    formula: 'K(Mg,Fe)₃(AlSi₃O₁₀)(OH)₂',
    typicalOccurrence: 'Ubiquitous in granites, diorites, gneisses, schists, and calc-alkaline volcanic rocks.',
    imageUrl: 'https://images.unsplash.com/photo-1525857597365-5f6dbff2e36e?auto=format&fit=crop&w=900&q=80',
    imageCaption: 'Dark brown-black book of biotite mica displaying vitreous to sub-metallic luster on basal cleavage surfaces.',
    geologicalFacts: [
      'Named in honor of French physicist and mathematician Jean-Baptiste Biot, who investigated the optical properties of mica.',
      'Widely utilized by geologists for K-Ar and ⁴⁰Ar/³⁹Ar geochronological dating, dating when mountain belts cooled below ~300°C.',
      'Weathering of biotite produces the golden sparkles often mistaken by novice gold panners for real gold ("fool\'s gold").',
    ],
  },
  'min-phlogopite': {
    formula: 'KMg₃(AlSi₃O₁₀)(OH)₂',
    typicalOccurrence: 'Metamorphosed dolomitic limestones, ultramafic kimberlites, lamproites, and mantle xenoliths.',
    imageUrl: 'https://images.unsplash.com/photo-1590412200988-a436970781fa?auto=format&fit=crop&w=900&q=80',
    imageCaption: 'Bronze-brown cleavage plates of phlogopite mica in crystalline calcite marble.',
    geologicalFacts: [
      'The magnesium endmember of the trioctahedral mica group; name derives from the Greek "phlogopos" (fire-like) in reference to its reddish-amber tint.',
      'A key mineral in mantle kimberlite diamonds, providing proof of metasomatic hydration of the deep subcontinental lithospheric mantle.',
      'Used commercially in industrial brake linings and heat shields due to its ability to withstand temperatures over 900°C without degassing.',
    ],
  },
  'min-kaolinite': {
    formula: 'Al₂Si₂O₅(OH)₄',
    typicalOccurrence: 'Hydrothermal alteration zones of granites, weathered feldspathic weathering profiles, and residual clay deposits (Cornwall UK, Georgia USA).',
    imageUrl: 'https://images.unsplash.com/photo-1567095761054-7a02e69e5c43?auto=format&fit=crop&w=900&q=80',
    imageCaption: 'Soft, chalky-white massive kaolinite clay hand specimen with earthy luster.',
    geologicalFacts: [
      'Named after Gaoling (Kao-ling) village in Jiangxi Province, China, where it was quarried for centuries to manufacture exquisite fine Chinese porcelain.',
      'Forms by the intense chemical weathering of potassium feldspar in warm, wet climates: 2KAlSi₃O₈ + 2H⁺ + 9H₂O → Al₂Si₂O₅(OH)₄ + 2K⁺ + 4H₄SiO₄.',
      'Has a very low shrink-swell capacity, making it a critical ingredient in glossy paper coating, pharmaceuticals (Kaopectate), and ceramics.',
    ],
  },
  'min-chlorite': {
    formula: '(Mg,Fe)₅Al(AlSi₃O₁₀)(OH)₈',
    typicalOccurrence: 'Greenschist facies metamorphic rocks, hydrothermally altered basaltic seafloor, and amygdule fillings in lavas.',
    imageUrl: 'https://images.unsplash.com/photo-1533038590840-1cde6e668a91?auto=format&fit=crop&w=900&q=80',
    imageCaption: 'Forest-green foliar crystal aggregate of clinochlore chlorite displaying pearly luster.',
    geologicalFacts: [
      'Gives "greenschist" and greenstones their signature color; name comes from the Greek "chloros" (χλωρός), meaning green.',
      'Forms by low-temperature hydrothermal alteration of pyroxene, amphibole, and biotite in oceanic basalts and volcanic rocks.',
      'Under the polarizing microscope, chlorite frequently displays anomalous interference colors (Prussian "Berlin blue" or tobacco brown).',
    ],
  },
  'min-serpentine': {
    formula: 'Mg₃Si₂O₅(OH)₄',
    typicalOccurrence: 'Serpentinized mantle peridotites, ophiolite suture zones, hydrothermal subduction channels, and seafloor fracture zones.',
    imageUrl: 'https://images.unsplash.com/photo-1588345921523-c2dcdb7f1dcd?auto=format&fit=crop&w=900&q=80',
    imageCaption: 'Mottled green polished serpentine specimen displaying smooth, waxy, scaly serpent-like surface texture.',
    geologicalFacts: [
      'Named after its mottled green appearance resembling snakeskin; official state rock of California.',
      'Formed by the exothermic hydration of mantle olivine: 2Mg₂SiO₄ + 3H₂O → Mg₃Si₂O₅(OH)₄ + Mg(OH)₂. This reaction produces hydrogen gas and methane, fueling primitive microbial life in deep-sea Lost City vents.',
      'The fibrous polymorph chrysotile was historically mined as commercial white asbestos.',
    ],
  },
  'min-magnetite': {
    formula: 'Fe₃O₄ (Fe²⁺Fe₂³⁺O₄)',
    typicalOccurrence: 'Accessory mineral in virtually all igneous rocks; Banded Iron Formations, contact metasomatic skarns, and black beach placers.',
    imageUrl: 'https://images.unsplash.com/photo-1525857597365-5f6dbff2e36e?auto=format&fit=crop&w=900&q=80',
    imageCaption: 'Sharp octahedral metallic black magnetite crystals exhibiting strong natural ferromagnetism on matrix.',
    geologicalFacts: [
      'Naturally magnetized pieces of magnetite are called "lodestones", which allowed ancient Chinese inventors and European sailors to invent the magnetic compass.',
      'Contains 72.4 wt% elemental iron, making it the most iron-rich of all commercial iron ore minerals.',
      'Migratory organisms (homing pigeons, honeybees, salmon, and magnetotactic bacteria) synthesize microscopic magnetite nanocrystals in their bodies to navigate using Earth\'s magnetic field.',
    ],
  },
  'min-hematite': {
    formula: 'Fe₂O₃',
    typicalOccurrence: 'Banded Iron Formations (Hamersley Australia, Lake Superior), hydrothermal veins, volcanic fumaroles, and weathered soil profiles.',
    imageUrl: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=900&q=80',
    imageCaption: 'Brilliant metallic specular hematite with glistening mirror-like micaceous plates, showing blood-red streak.',
    geologicalFacts: [
      'Name comes from the Greek "haima" (αἷμα, blood) because even though crystals are silvery-black, its streak on an unglazed porcelain plate is always blood red.',
      'NASA\'s Mars rover *Opportunity* discovered millions of hematite concretions ("Martian blueberries") on Meridiani Planum, proving that liquid water once flowed on Mars.',
      'The red ochre variety was used by Paleolithic humans over 100,000 years ago as the earliest cave painting pigment and ritual cosmetic.',
    ],
  },
  'min-ilmenite': {
    formula: 'FeTiO₃',
    typicalOccurrence: 'Gabbros, anorthosites, continental flood basalts, and heavy mineral black sand beach placers.',
    imageUrl: 'https://images.unsplash.com/photo-1590412200988-a436970781fa?auto=format&fit=crop&w=900&q=80',
    imageCaption: 'Metallic iron-black submetallic crystal mass of ilmenite from a titanium-rich anorthosite.',
    geologicalFacts: [
      'The world\'s foremost ore of titanium metal and titanium dioxide (TiO₂) white pigment used in paints, plastics, and sunscreens.',
      'Named after the Ilmen Mountains in the southern Urals of Russia where it was first discovered.',
      'Abundant in lunar mare basalts; NASA scientists investigate lunar ilmenite as an in-situ source of oxygen for future lunar astronaut bases.',
    ],
  },
  'min-chromite': {
    formula: 'FeCr₂O₄',
    typicalOccurrence: 'Podiform chromitites in ophiolites, stratiform layers in large mafic-ultramafic intrusions (Bushveld, Stillwater, Great Dyke).',
    imageUrl: 'https://images.unsplash.com/photo-1567095761054-7a02e69e5c43?auto=format&fit=crop&w=900&q=80',
    imageCaption: 'Granular pitch-black metallic chromite seam embedded in yellowish-green weathered dunite.',
    geologicalFacts: [
      'The single commercially viable ore of chromium, indispensable for producing stainless steel, superalloys, and chrome plating.',
      'Forms pure stratiform "reefs" in layered intrusions, such as the famous UG2 chromitite reef in South Africa\'s Bushveld Complex.',
      'Because of its extreme chemical resistance and high crystallization temperature (~1,600°C), chromite grains preserve pristine Archean geochemical signatures.',
    ],
  },
  'min-rutile': {
    formula: 'TiO₂',
    typicalOccurrence: 'High-grade metamorphic eclogites, granulites, hydrothermal quartz veins, and heavy mineral beach sands.',
    imageUrl: 'https://images.unsplash.com/photo-1533038590840-1cde6e668a91?auto=format&fit=crop&w=900&q=80',
    imageCaption: 'Golden acicular needles of rutile radiating inside a clear water-clear quartz crystal (rutilated quartz).',
    geologicalFacts: [
      'Has one of the highest refractive indices of any known mineral (n = 2.61 to 2.90), far exceeding that of diamond (2.42).',
      'Microscopic oriented needle inclusions of rutile in corundum produce the stunning six-rayed star effect in "star sapphires" and "star rubies" (asterism).',
      'The concentration of zirconium in metamorphic rutile is an exceptionally accurate geothermometer for measuring peak metamorphic temperatures.',
    ],
  },
  'min-spinel': {
    formula: 'MgAl₂O₄',
    typicalOccurrence: 'Metamorphosed dolomitic limestones, marble skarns, mantle peridotites, and gem gravels (Mogok Myanmar, Sri Lanka, Tajikistan).',
    imageUrl: 'https://images.unsplash.com/photo-1525857597365-5f6dbff2e36e?auto=format&fit=crop&w=900&q=80',
    imageCaption: 'Sharp ruby-red octahedral spinel crystal perched on white crystalline marble matrix.',
    geologicalFacts: [
      'Historically confused with ruby; the famous 170-carat "Black Prince\'s Ruby" in the British Imperial State Crown is actually a magnificent red spinel.',
      'Gives its name to the entire Spinel Group of cubic minerals, which includes magnetite, chromite, and gahnite.',
      'Mantle spinel peridotites record crystallization pressures between 1.0 and 2.0 GPa (~30 to 60 km depth), bridging plagioclase and garnet stability fields.',
    ],
  },
  'min-calcite': {
    formula: 'CaCO₃',
    typicalOccurrence: 'Limestones, marbles, chalk, carbonatites, cave formations (stalactites/stalagmites), and hydrothermal veins.',
    imageUrl: 'https://images.unsplash.com/photo-1588345921523-c2dcdb7f1dcd?auto=format&fit=crop&w=900&q=80',
    imageCaption: 'Transparent rhombohedral Iceland spar calcite crystal exhibiting spectacular double refraction of text beneath it.',
    geologicalFacts: [
      'Exhibits dramatic double refraction (birefringence); an optical crystal placed over printed words splits the light to produce two distinct parallel images.',
      'Viking sagas tell of a magical "sunstone" used by navigators to locate the sun on fog-bound Arctic voyages; optical experiments prove clear Iceland spar calcite crystals fit this role.',
      'Effervesces vigorously (fizzes) with cold dilute hydrochloric acid (HCl), releasing CO₂ gas—the classic field diagnostic test for carbonate rocks.',
    ],
  },
  'min-dolomite': {
    formula: 'CaMg(CO₃)₂',
    typicalOccurrence: 'Dolostone sedimentary beds, altered carbonate reefs, hydrothermal veins, and dolomitic marbles.',
    imageUrl: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=900&q=80',
    imageCaption: 'Curved saddle-shaped pearly pink dolomite crystals grouped on matrix.',
    geologicalFacts: [
      'Named after the French naturalist Déodat de Dolomieu (1750–1801), who discovered the mineral in the stunning mountain peaks now known as the Italian Dolomites.',
      'Distinguished from calcite in the field because it only effervesces weakly with cold acid, but reacts vigorously if the rock is powdered or the acid is warmed.',
      'Frequently exhibits diagnostic curved, saddle-shaped crystal faces ("saddle dolomite") caused by lattice strain during hydrothermal growth.',
    ],
  },
  'min-siderite': {
    formula: 'FeCO₃',
    typicalOccurrence: 'Sedimentary ironstone nodules, coal-bed ironstone balls, low-temperature hydrothermal veins, and metamorphic banded formations.',
    imageUrl: 'https://images.unsplash.com/photo-1590412200988-a436970781fa?auto=format&fit=crop&w=900&q=80',
    imageCaption: 'Tan-brown rhombohedral crystals of siderite with vitreous luster on sulfide matrix.',
    geologicalFacts: [
      'Name derived from the Greek "sideros" (σίδηρος), meaning iron, containing 48.2 wt% iron.',
      'Historically formed the backbone of the British Industrial Revolution, mined from sedimentary "blackband ironstone" seams in the coal measures of Wales and Yorkshire.',
      'Has a high specific gravity (3.96 g/cm³), making it noticeably heavy in the hand compared to calcite or dolomite.',
    ],
  },
  'min-magnesite': {
    formula: 'MgCO₃',
    typicalOccurrence: 'Hydrothermally altered ultramafic serpentinites, cryptocrystalline nodular deposits, and metamorphosed evaporites.',
    imageUrl: 'https://images.unsplash.com/photo-1567095761054-7a02e69e5c43?auto=format&fit=crop&w=900&q=80',
    imageCaption: 'Porcelain-like white nodular magnesite hand specimen with unglazed chalky fracture.',
    geologicalFacts: [
      'Crucial industrial source of refractory magnesium oxide (magnesia, MgO), used to line high-temperature steelmaking furnaces at >1,800°C.',
      'Forms when CO₂-rich fluids circulate through mantle peridotite rocks: serpentine + CO₂ → magnesite + quartz + water.',
      'Recognized as a premier natural mineral for industrial carbon mineralization to permanently sequester atmospheric carbon dioxide as solid stone.',
    ],
  },
  'min-fluorapatite': {
    formula: 'Ca₅(PO₄)₃F',
    typicalOccurrence: 'Granitic pegmatites, carbonatite complexes (Kola Peninsula), marine phosphorite sedimentary beds, and tooth enamel.',
    imageUrl: 'https://images.unsplash.com/photo-1533038590840-1cde6e668a91?auto=format&fit=crop&w=900&q=80',
    imageCaption: 'Hexagonal prismatic teal-blue fluorapatite crystal with sharp basal pinacoid termination.',
    geologicalFacts: [
      'Name comes from the Greek "apatao" (ἀπατάω), meaning "to deceive", because its diverse colors and shapes frequently led miners to mistake it for beryl, olivine, or topaz.',
      'Defines hardness 5 on the Mohs hardness scale.',
      'Biological apatite (hydroxylapatite / fluorapatite) forms the mineral framework of human bones and the hard protective enamel of your teeth.',
    ],
  },
  'min-halite': {
    formula: 'NaCl',
    typicalOccurrence: 'Sedimentary evaporite basins, salt domes, salars (Salar de Uyuni Bolivia, Death Valley, Zechstein Sea Europe).',
    imageUrl: 'https://images.unsplash.com/photo-1525857597365-5f6dbff2e36e?auto=format&fit=crop&w=900&q=80',
    imageCaption: 'Transparent cubic crystals of halite (rock salt) showing perfect 90° cubic cleavage.',
    geologicalFacts: [
      'Common table salt; essential to human biological life and historically so valuable it served as Roman currency (giving rise to the word "salary").',
      'Displays perfect {100} cubic cleavage: no matter how many times you strike a crystal with a hammer, it breaks into smaller cubes.',
      'Under tectonic burial pressure, deeply buried salt beds behave as a viscous fluid, flowing upward like lava lamps to form colossal subterranean "salt domes" that trap vast petroleum reserves.',
    ],
  },
};

/**
 * Enriches a Rock reference with visual and geological details
 */
export function getEnrichedRock(rock: RockReference): RockReference {
  const visual = VISUAL_DATA_MAP[rock.id];
  const dbRefs = rock.databaseRefs || getDatabaseRefs(rock.id, rock.name);
  return {
    ...rock,
    formula: visual?.formula || rock.formula || rock.keyMinerals.join(' + '),
    typicalOccurrence: visual?.typicalOccurrence || rock.typicalOccurrence || rock.typicalTectonicSetting || 'Geological formation',
    imageUrl: visual?.imageUrl || rock.imageUrl || 'https://images.unsplash.com/photo-1525857597365-5f6dbff2e36e?auto=format&fit=crop&w=800&q=80',
    imageCaption: visual?.imageCaption || rock.imageCaption || `${rock.name} hand specimen`,
    geologicalFacts: visual?.geologicalFacts || rock.geologicalFacts || [
      `${rock.name} is classified under ${rock.category} lithology.`,
      `Calibrated using geochemical reference compositions from GEOROC and USGS datasets.`,
      `Characteristic key minerals include ${rock.keyMinerals.slice(0, 3).join(', ')}.`,
    ],
    databaseRefs: dbRefs,
  };
}

/**
 * Enriches a Mineral reference with visual and geological details
 */
export function getEnrichedMineral(mineral: MineralReference): MineralReference {
  const visual = VISUAL_DATA_MAP[mineral.id];
  const dbRefs = mineral.databaseRefs || getDatabaseRefs(mineral.id, mineral.name);
  return {
    ...mineral,
    formula: visual?.formula || mineral.formula,
    typicalOccurrence: visual?.typicalOccurrence || mineral.typicalOccurrence || mineral.description,
    imageUrl: visual?.imageUrl || mineral.imageUrl || 'https://images.unsplash.com/photo-1567225557594-88d73e55f2cb?auto=format&fit=crop&w=800&q=80',
    imageCaption: visual?.imageCaption || mineral.imageCaption || `${mineral.name} crystal specimen`,
    geologicalFacts: visual?.geologicalFacts || mineral.geologicalFacts || [
      `${mineral.name} belongs to the ${mineral.group} group with ${mineral.crystalSystem} crystal symmetry.`,
      `Standard chemical formula is ${mineral.formula}.`,
      mineral.solidSolution ? `Exhibits solid solution series: ${mineral.solidSolution}.` : `Commonly found in high-grade crustal and mantle rocks.`,
    ],
    databaseRefs: dbRefs,
  };
}

/**
 * Enriches any generic reference item
 */
export function getEnrichedSpecimen(
  item: RockReference | MineralReference
): RockReference | MineralReference {
  if ('category' in item) {
    return getEnrichedRock(item as RockReference);
  }
  return getEnrichedMineral(item as MineralReference);
}
